# -*- coding: utf-8 -*-
# Ampliación de cobertura: nombres propios y compuestos capitalizados.

# (1) Formas capitalizadas que son en realidad TÉRMINOS TRADUCIBLES.
#     Se mueven al diccionario principal con esta glosa indonesia. [B]
TERM_MOVE = {
    "Abar Kaaruien": "Injil, Kabar Baik",
    "Amang": "Bapa (sebutan bagi Allah)",
    "Amang Kasuruan": "Allah; Tuhan Allah",
    "Amang-Kasuruan é tou Israel": "Allah orang Israel",
    "Amang Kasuruan si Makakawasa": "Allah Yang Mahakuasa",
    "Amang Kasuruan si Mangko-wangko'": "Allah Yang Mahatinggi",
    "Apo'": "Tuhan (gelar)",
    "Apo' Yesus": "Tuhan Yesus",
    "Asu in talun": "serigala (harfiah: anjing hutan)",
    "Balé Le'nas": "Bait Suci, Rumah Allah",
    "Walé Le'nas": "Bait Suci, Rumah Allah",
    "Kamar Le'nas": "Ruang Kudus (Bait Suci)",
    "Kitap Le'nas": "Kitab Suci",
    "Casuruan": "Tuhan",
    "Kasuruan": "Tuhan",
    "Colano": "raja",
    "Kolano, kakolanoan": "raja; kerajaan",
    "Le'nas": "kudus, suci",
    "Makakawasa": "Yang Mahakuasa",
    "Mesias": "Mesias",
    "Roh": "Roh",
    "Roh i Amang Kasuruan": "Roh Allah",
    "Roh Le'nas": "Roh Kudus",
    "Ténda Pengaapo'an": "Kemah Pertemuan, Kemah Suci",
    "Toyaang": "anak",
    "Toyaang i Tou": "Anak Manusia",
    "Tuang": "tuan",
    "Tuura in zaitun": "pohon zaitun",
    "Imam": "imam",
    "Kaisar": "Kaisar, Maharaja Roma",
    "Caisar": "Kaisar, Maharaja Roma",
    "Kristus": "Kristus, Mesias",
    "Krésten": "orang Kristen",
    "Farisi": "orang Farisi",
    "Saduki": "orang Saduki",
    "Yahudi": "orang Yahudi",
    "Ibrani": "orang/bahasa Ibrani",
    "Legion": "legiun (pasukan)",
    "Mina": "mina (satuan uang)",
    "Sangapulu": "sepuluh",
    "Makangaran": "yang bernama",
}

# (2) Nombres propios genuinos -> tipo.  orang=persona, tempat=lugar,
#     bangsa=pueblo/nación, lain=otro (ángel, título, moneda, etc.)
PROP = {
 "Abadon":"lain","Abi":"orang","Abia":"orang","Abihud":"orang","Abilene":"tempat",
 "Abraham":"orang","Abyatar":"orang","Adam":"orang","Adi":"orang","Admin":"orang",
 "Agustus":"orang","Ahas":"orang","Akhaya":"tempat","Akhim":"orang","Akwila":"orang",
 "Aleksander":"orang","Alfeus":"orang","Aminadab":"orang","Amitai":"orang","Amon":"orang",
 "Amos":"orang","Andreas":"orang","Antiokhia":"tempat","Antipas":"orang","Apolos":"orang",
 "Arimatea":"tempat","Arkelaus":"orang","Arni":"orang","Arpakhsad":"orang","Artemas":"orang",
 "Asa":"orang","Asia":"tempat","Asyer":"orang","Atena":"tempat","Ayub":"orang","Azor":"orang",
 "Babel":"tempat","Balak":"orang","Barabas":"orang","Barnabas":"orang","Bartimeus":"orang",
 "Bartolomeus":"orang","Beelzebul":"lain","Benyamin":"orang","Berekhya":"orang","Betania":"tempat",
 "Betfage":"tempat","Betlehem":"tempat","Betsaida":"tempat","Bileam":"orang","Bitinia":"tempat",
 "Boas":"orang","Daniel":"orang","Daud":"orang","Demas":"orang","Demetrius":"orang",
 "Diotrefes":"orang","Eber":"orang","Ebulus":"orang","Efesus":"tempat","Efrat":"tempat",
 "Eleazar":"orang","Eli":"orang","Elia":"orang","Eliezer":"orang","Elisa":"orang",
 "Elisabet":"orang","Eliud":"orang","Elmadam":"orang","Elyakim":"orang","Enos":"orang",
 "Er":"orang","Erastus":"orang","Eunike":"orang","Fanuel":"orang","Fenesia":"tempat",
 "Figelus":"orang","Filadelfia":"tempat","Filetus":"orang","Filipi":"tempat","Pilipi":"tempat",
 "Gabriel":"lain","Gad":"orang","Gadara":"tempat","Galatia":"tempat","Galilea":"tempat",
 "Gayus":"orang","Genesaret":"tempat","Gerasa":"tempat","Getsemani":"tempat","Gio":"orang",
 "Gog":"lain","Gomora":"tempat","Habel":"orang","Hana":"orang","Hanas":"orang",
 "Harmagedon":"tempat","Harun":"orang","Hawa":"orang","Henokh":"orang","Hermogenes":"orang",
 "Herodes":"orang","Herodes Antipas":"orang","Herodias":"orang","Hesli":"orang","Hezron":"orang",
 "Himeneus":"orang","Hizkia":"orang","Idumea":"tempat","Ikonium":"tempat","Imanuel":"orang",
 "Isakhar":"orang","Ishak":"orang","Iskariot":"lain","Israel":"bangsa","Iturea":"tempat",
 "Iutus":"orang","Izebel":"orang","Kain":"orang","Kaisarea":"tempat","Kanaan":"tempat",
 "Kapadokia":"tempat","Kapernaum":"tempat","Karpus":"orang","Kayafas":"orang","Kelinganake":"orang",
 "Kenan":"orang","Khorazim":"tempat","Khuza":"orang","Kirene":"tempat","Kirenius":"orang",
 "Klaudia":"orang","Kloe":"orang","Korah":"orang","Korintus":"tempat","Kosam":"orang",
 "Kreskes":"orang","Kreta":"tempat","Krispus":"orang","Lamekh":"orang","Laodikia":"tempat",
 "Lewi":"orang","Linus":"orang","Lisanias":"orang","Listra":"tempat","Lois":"orang",
 "Lot":"orang","Lukas":"orang","Maat":"orang","Magadan":"tempat","Magdala":"tempat",
 "Magog":"lain","Mahalaleel":"orang","Makedonia":"tempat","Malkhi":"orang","Manasye":"orang",
 "Mandé":"orang","Mape'dis":"lain","Maria":"orang","Markus":"orang","Matan":"orang",
 "Matat":"orang","Matata":"orang","Matica":"orang","Matius":"orang","Melea":"orang",
 "Mesir":"tempat","Metusalah":"orang","Mikhael":"lain","Miletus":"tempat","Musa":"orang",
 "Naaman":"orang","Naftali":"orang","Nagai":"orang","Nahason":"orang","Nahor":"orang",
 "Nahum":"orang","Nain":"tempat","Natan":"orang","Nazaret":"tempat","Neri":"orang",
 "Nikolaus":"orang","Nikopolis":"tempat","Ninewe":"tempat","Niniwe":"tempat","Nuh":"orang",
 "Obed":"orang","Onesiforus":"orang","Pakakamangenko":"orang","Pakakumisinku":"orang",
 "Patmos":"tempat","Paulus":"orang","Peleg":"orang","Peres":"orang","Pergamus":"tempat",
 "Petrus":"orang","Pilatus":"orang","Pontus":"tempat","Priska":"orang","Pudes":"orang",
 "Rahab":"orang","Rahel":"orang","Ram":"orang","Rama":"tempat","Rehabeam":"orang",
 "Rehu":"orang","Resa":"orang","Roma":"tempat","Ruben":"orang","Rufus":"orang","Rut":"orang",
 "Salmon":"orang","Salome":"orang","Salomo":"orang","Sara":"orang","Sardis":"tempat",
 "Sarfat":"tempat","Sealtiel":"orang","Sem":"orang","Serug":"orang","Set":"orang",
 "Sidon":"tempat","Silas":"orang","Simei":"orang","Simeon":"orang","Simon":"orang",
 "Sion":"tempat","Siria":"tempat","Smirna":"tempat","Sodom":"tempat","Sostenes":"orang",
 "Sowateno":"lain","Stefanus":"orang","Sumasani":"tempat","Susan":"orang","Taar":"lain",
 "Tadeus":"orang","Tamar":"orang","Tarsis":"tempat","Terah":"orang","Tesalonika":"tempat",
 "Tiatira":"tempat","Tiberius":"orang","Tikhikus":"orang","Timeus":"orang","Timotius":"orang",
 "Tirus":"tempat","Tomas":"orang","Trakhonitis":"tempat","Troas":"tempat","Trofimus":"orang",
 "Uli-ulit":"lain","Uria":"orang","Uzia":"orang","Yafo":"tempat","Yairus":"orang",
 "Yakobus":"orang","Yakub":"orang","Yambres":"orang","Yanai":"orang","Yanes":"orang",
 "Yared":"orang","Yekhonya":"orang","Yeremia":"orang","Yerikho":"tempat","Yerusalem":"tempat",
 "Yesaya":"orang","Yesus":"orang","Yoda":"orang","Yohana":"orang","Yohanan":"orang",
 "Yohanes":"orang","Yonam":"orang","Yoram":"orang","Yordan":"tempat","Yorim":"orang",
 "Yosafat":"orang","Yosekh":"orang","Yoses":"orang","Yosia":"orang","Yotam":"orang",
 "Yudas":"orang","Yudea":"tempat","Yunus":"orang","Yusup":"orang","Zadok":"orang",
 "Zakaria":"orang","Zebedeus":"orang","Zebulon":"orang","Zenas":"orang","Zerah":"orang",
 "Zerubabel":"orang",
}

# (3) Nombre indonesio estándar donde difiere de la forma tontémboan.
PROP_ID = {
 "Caisar":"Kaisar","Pilipi":"Filipi","Yusup":"Yusuf","Krésten":"Kristen",
 "Fenesia":"Fenisia","Sumasani":"Samaria","Ninewe":"Niniwe","Arkelaus":"Arkhelaus",
 "Abadon":"Abadon (malaikat jurang maut)","Beelzebul":"Beelzebul (penghulu setan)",
 "Gabriel":"Gabriel (malaikat)","Mikhael":"Mikhael (malaikat)",
 "Iskariot":"Iskariot (julukan Yudas)",
}
