# -*- coding: utf-8 -*-
# Nombres propios y términos capitalizados de Yanesha'.
#
# GENERADO — no editar a mano. Se regenera con:
#     python tools/gen_prop_map.py ame
# Las correcciones van en OVERRIDE, dentro de ese script.
#
# Tipos y formas castellanas derivados de Category/Domain de la lista Major
# de Paratext y de la glosa de BiblicalTermsEs.xml.

# forma -> persona (orang) / lugar (tempat) / pueblo (bangsa) / otros (lain)
PROP = {
    "Aarón":                        "orang",
    "Abias":                        "orang",
    "Abiatar":                      "orang",
    "Abidanab":                     "orang",
    "Abiel":                        "orang",
    "Abigail":                      "orang",
    "Abinadab":                     "orang",
    "Abisai":                       "orang",
    "Abner":                        "orang",
    "Adriel":                       "orang",
    "Adulam":                       "tempat",
    "Afec":                         "tempat",
    "Afia":                         "orang",
    "Agag":                         "orang",
    "Ahias":                        "orang",
    "Ahimaas":                      "orang",
    "Ahimelec":                     "orang",
    "Ahimélec":                     "orang",
    "Ahinoam":                      "orang",
    "Ahinóam":                      "orang",
    "Ahitob":                       "orang",
    "Ajalón":                       "tempat",
    "Amalec":                       "orang",
    "Amalecnesha":                  "orang",
    "Amalecot̃":                    "bangsa",
    "Amonita":                      "bangsa",
    "Amonitaneshá":                 "orang",
    "Amorreyoneshá":                "bangsa",
    "Ana":                          "orang",
    "Aquis":                        "orang",
    "Aquísesho":                    "orang",
    "Arabá":                        "tempat",
    "Ascalón":                      "tempat",
    "Asdotómarneshá":               "tempat",
    "Astarot":                      "lain",
    "Atac":                         "tempat",
    "Azeca":                        "tempat",
    "Baal":                         "lain",
    "Barac":                        "orang",
    "Becorat":                      "orang",
    "Beerseba":                     "tempat",
    "Belen":                        "bangsa",
    "Beleñómarnesha":               "bangsa",
    "Belén":                        "tempat",
    "Beléño":                       "tempat",
    "Benjamin":                     "orang",
    "Besor":                        "tempat",
    "Bet-avén":                     "tempat",
    "Bet-car":                      "tempat",
    "Bet-el":                       "tempat",
    "Bet-horón":                    "tempat",
    "Bet-sem̃so":                   "bangsa",
    "Bet-sem̃somarneshá":           "bangsa",
    "Bet-sán":                      "tempat",
    "Bezec":                        "tempat",
    "Boses":                        "tempat",
    "Caleb":                        "orang",
    "Calef":                        "tempat",
    "Carmel":                       "orang",
    "Cis":                          "orang",
    "Corasán":                      "tempat",
    "Dagón":                        "lain",
    "Dan":                          "tempat",
    "David":                        "orang",
    "Davidpá":                      "orang",
    "Doeg":                         "orang",
    "Eben-ezer":                    "tempat",
    "Ecrón":                        "tempat",
    "Ecrónneshá":                   "bangsa",
    "Edomita":                      "bangsa",
    "Efrain":                       "orang",
    "Efraiñenátar":                 "bangsa",
    "Efrayeñenatar":                "bangsa",
    "Ejiptot̃ Ejiptomarnesha":      "bangsa",
    "Elcana":                       "orang",
    "Eleazar":                      "orang",
    "Eli":                          "orang",
    "Eliab":                        "orang",
    "Eliú":                         "orang",
    "Elí":                          "orang",
    "Elísho":                       "orang",
    "En-gadi":                      "tempat",
    "Endor":                        "tempat",
    "Eshtemoa":                     "tempat",
    "Faraón":                       "orang",
    "Finees":                       "orang",
    "Gabaa":                        "tempat",
    "Gad":                          "orang",
    "Galaad":                       "tempat",
    "Galim":                        "tempat",
    "Gat":                          "tempat",
    "Gatomarneshá":                 "tempat",
    "Gaza":                         "tempat",
    "Gezritaneshá":                 "bangsa",
    "Gilboa":                       "tempat",
    "Gilgal":                       "tempat",
    "Gilgalo":                      "tempat",
    "Goliat":                       "orang",
    "Haquila":                      "tempat",
    "Havila":                       "orang",
    "Hazor":                        "tempat",
    "Hebrón":                       "tempat",
    "Hititaneshá":                  "bangsa",
    "Horma":                        "tempat",
    "Icabot":                       "orang",
    "Isaí":                         "orang",
    "Isaíshó":                      "orang",
    "Israel":                       "orang",
    "Israelecop":                   "orang",
    "Israeleneshot̃":               "orang",
    "Israeleneshá":                 "orang",
    "Israeleneshácop":              "orang",
    "Israelesho":                   "orang",
    "Israeleshot̃":                 "orang",
    "Israelñapa":                   "orang",
    "Isúi":                         "orang",
    "Jabes":                        "tempat",
    "Jabesómarneshá":               "tempat",
    "Jatir":                        "tempat",
    "Jerahmeel":                    "bangsa",
    "Jeroham":                      "orang",
    "Jerusaleño":                   "tempat",
    "Jerusalén":                    "tempat",
    "Jezreel":                      "tempat",
    "Jezreelita":                   "bangsa",
    "Joab":                         "orang",
    "Joel":                         "orang",
    "Jonatán":                      "orang",
    "Jonatánpa":                    "orang",
    "Jordán":                       "tempat",
    "Josué":                        "bangsa",
    "Judá":                         "orang",
    "Levita":                       "bangsa",
    "Malquisúa":                    "orang",
    "Maoc":                         "orang",
    "Matri":                        "bangsa",
    "Maón":                         "tempat",
    "Merab":                        "orang",
    "Mical":                        "orang",
    "Micmas":                       "tempat",
    "Micmaso":                      "tempat",
    "Migrón":                       "tempat",
    "Mispá":                        "tempat",
    "Mizpa":                        "tempat",
    "Moab":                         "orang",
    "Moises":                       "orang",
    "Nabal":                        "orang",
    "Ner":                          "orang",
    "Nob":                          "tempat",
    "Ofni":                         "orang",
    "Penina":                       "orang",
    "Quenita":                      "bangsa",
    "Quereteyoneshá":               "bangsa",
    "Quiriat-jearim":               "tempat",
    "Racal":                        "tempat",
    "Rama":                         "tempat",
    "Ramat":                        "tempat",
    "Ramatáyeño":                   "tempat",
    "Ramot":                        "tempat",
    "Raquel":                       "orang",
    "Saalim":                       "tempat",
    "Saaraim":                      "tempat",
    "Salisa":                       "tempat",
    "Sama":                         "orang",
    "Samuel":                       "orang",
    "Samueleshonet̃":               "orang",
    "Saúl":                         "orang",
    "Saúleshó":                     "orang",
    "Secú":                         "tempat",
    "Sen":                          "tempat",
    "Sene":                         "tempat",
    "Siclag":                       "tempat",
    "Sifmot":                       "tempat",
    "Silo":                         "tempat",
    "Silot̃":                       "tempat",
    "Sunem":                        "tempat",
    "Sísara":                       "orang",
    "Zeror":                        "orang",
    "Zif":                          "tempat",
    "Zifomarneshá":                 "bangsa",
}

# forma -> forma castellana estándar (solo cuando difiere de la vernácula)
PROP_ID = {
    "Abias":                        "Abías",
    "Abidanab":                     "Abinadab",
    "Afia":                         "Afíah",
    "Ahias":                        "Ahías",
    "Ahimelec":                     "Ahimélec",
    "Ahinoam":                      "Ahinóam",
    "Ahitob":                       "Ahitub",
    "Ajalón":                       "Aialón",
    "Amalecnesha":                  "Amalec",
    "Amalecot̃":                    "Amalecita",
    "Amonitaneshá":                 "Amonita",
    "Amorreyoneshá":                "Amorreos",
    "Aquis":                        "Aquís",
    "Aquísesho":                    "Aquís",
    "Asdotómarneshá":               "Asdod",
    "Astarot":                      "Astarté",
    "Azeca":                        "Azecá",
    "Belen":                        "Betlemita",
    "Beleñómarnesha":               "Betlemita",
    "Beléño":                       "Belén",
    "Benjamin":                     "Benjamín",
    "Bet-el":                       "Betel",
    "Bet-sem̃so":                   "de Bet-semes",
    "Bet-sem̃somarneshá":           "de Bet-semes",
    "Bezec":                        "Bézec",
    "Boses":                        "Bosés",
    "Calef":                        "Caleb",
    "Cis":                          "Quis",
    "Davidpá":                      "David",
    "Eben-ezer":                    "Eben-ézer",
    "Ecrónneshá":                   "Ecronitas",
    "Efrain":                       "Efraín",
    "Efraiñenátar":                 "Efraimita",
    "Efrayeñenatar":                "Efraimita",
    "Ejiptot̃ Ejiptomarnesha":      "Egipcio",
    "Elcana":                       "Elcaná",
    "Eli":                          "Elí",
    "Eliú":                         "Elihú",
    "Elísho":                       "Elí",
    "Eshtemoa":                     "Estemoa",
    "Gabaa":                        "Guibeá",
    "Gatomarneshá":                 "Gat",
    "Gezritaneshá":                 "Gezrita",
    "Gilboa":                       "Guilboa",
    "Gilgal":                       "Guilgal",
    "Gilgalo":                      "Guilgal",
    "Haquila":                      "Haquilá",
    "Havila":                       "Havilá",
    "Hazor":                        "Hasor",
    "Hititaneshá":                  "Hitita",
    "Horma":                        "Hormá",
    "Icabot":                       "Icabod",
    "Isaí":                         "Jesé",
    "Isaíshó":                      "Jesé",
    "Israelecop":                   "Israel",
    "Israeleneshot̃":               "Israel",
    "Israeleneshá":                 "Israel",
    "Israeleneshácop":              "Israel",
    "Israelesho":                   "Israel",
    "Israeleshot̃":                 "Israel",
    "Israelñapa":                   "Israel",
    "Isúi":                         "Isví",
    "Jabes":                        "Jabés",
    "Jabesómarneshá":               "Jabés",
    "Jerahmeel":                    "Jerahmeelita",
    "Jerusaleño":                   "Jerusalén",
    "Jonatánpa":                    "Jonatán",
    "Matri":                        "Matrí",
    "Micmas":                       "Micmás",
    "Micmaso":                      "Micmás",
    "Mizpa":                        "Mispá",
    "Moab":                         "Amonita",
    "Moises":                       "Moisés",
    "Ofni":                         "Hofní",
    "Penina":                       "Peniná",
    "Quereteyoneshá":               "Quereteos",
    "Rama":                         "Ramá",
    "Ramat":                        "Ramat del Neguev",
    "Ramatáyeño":                   "Ramataim de Zofim",
    "Ramot":                        "Ramot del Négueb",
    "Salisa":                       "Salisá",
    "Sama":                         "Samá",
    "Samueleshonet̃":               "Samuel",
    "Saúleshó":                     "Saúl",
    "Silo":                         "Siló",
    "Silot̃":                       "Siló",
    "Zeror":                        "Seror",
    "Zifomarneshá":                 "Zifitas",
}

# capitalizadas que NO son nombres propios: vuelven al diccionario principal
TERM_MOVE = {
    "Achyotáñ":                                             "practicar adivinación, adivinación",
    "Acraret̃ asharet̃ puesé":                              "ungido",
    "Ahuócchátañ":                                          "plaga",
    "Ameñaña poñoc̈h":                                      "piadoso",
    "Amách sem̃chátatsto":                                  "temer, tener miedo",
    "Anets":                                                "ciudad",
    "Anmañet":                                              "carro, carreta",
    "Arrnomaret̃chá":                                       "maldecir",
    "Arrot̃étañ":                                           "ave",
    "Asrem̃":                                               "rodillo",
    "Besoshém póconc̈h":                                    "rebaño",
    "Beñsaréteñets":                                        "bendición",
    "Cahuallmat̃ achéñmoc":                                 "camello",
    "Chopapetspá":                                          "flecha",
    "Cochllet̃ollo":                                        "navaja (para rasurar)",
    "Cárr":                                                 "cayado, bastón",
    "Etamueñets":                                           "arar",
    "Eñotateñets":                                          "honrado, íntegro, perfecto, sin defecto, intachable",
    "Gách":                                                 "hacha",
    "Huaquesh":                                             "ganado",
    "Huaquësh":                                             "ganado, hato",
    "Mañorrmat̃ quellhue":                                  "cabrito, cabra joven",
    "Mellañot̃eñ":                                          "ángel",
    "Morrenteñets":                                         "favor; aprobación; piedad; gracia; bondad; misericordia; compasión",
    "Muec̈hop":                                             "eunuco, oficial de palacio, oficial",
    "Na nehuaménco":                                        "cuerno",
    "Parets":                                               "santo",
    "Pomorr atsetara":                                      "efod, delantal sagrado",
    "Pópartsoña":                                           "gloria del Señor, presencia de Dios",
    "P̃áqueshp̃ateño":                                      "salvación",
    "Queshpeñets":                                          "salvación",
    "Tsach apcomoret̃":                                     "tamarisco",
    "Yamomté":                                              "señor, amo",
    "Yellchep penqüeñtsem":                                 "calzoncillo de lino",
    "Yepapar parets":                                       "dios, Dios",
    "Yompor parets":                                        "dios, Dios",
    "¡llequëñtsa yocopbee!":                                "temer, tener miedo",
    "Ñeñt̃ entene ñeñt̃chá etsotatsá":                      "vidente, profeta",
    "Ñeñt̃ muetsenet att̃och esháret̃terra ochñaret̃":      "ofrenda de culpa",
    "Ñeñt̃ yepomuen yomporecop":                            "ofrenda de culpa",
    "Ñá nán póñoñ":                                         "hacer un voto, voto, promesa",
}
