# -*- coding: utf-8 -*-
# Greek/Hebrew lemma -> Indonesian gloss.  Keyed by BASE lemma (suffixes stripped).
# Meanings = standard NT/OT lexical meaning rendered into Bahasa Indonesia.

GK = {
    # --- articles/high-frequency handled by phrase/common ---
    "ὁδός": "jalan; ajaran, cara hidup",
    "αἰών": "zaman, masa; kekekalan",
    "αἰώνιος": "kekal, abadi",
    "βασιλεία": "kerajaan; pemerintahan",
    "θεός": "Allah",
    "οὐρανός": "sorga, langit",
    "κύριος": "Tuhan; tuan",
    "πνεῦμα": "roh; Roh; angin, napas",
    "ἀκάθαρτος": "najis, tidak tahir",
    "σάρξ": "daging; tubuh; kemanusiaan",
    "σωτηρία": "keselamatan",
    "υἱός": "anak (laki-laki); putra",
    "ἐπιθυμία": "keinginan, hawa nafsu",
    "Σατανᾶς": "Setan, Iblis",
    "Χριστός": "Kristus, Mesias",
    "αἴνεσις": "pujian",
    "αἴσθησις": "pengertian, daya membedakan",
    "αὐλέω": "meniup seruling",
    "αὐλή": "halaman, pelataran",
    "αὐλητής": "peniup seruling",
    "βάπτισμα": "baptisan",
    "βίβλος": "kitab, buku",
    "βαπτίζω": "membaptis",
    "βαπτιστής": "pembaptis",
    "βασίλειος": "kerajaan; istana raja",
    "βασίλισσα": "ratu",
    "βασιλεύς": "raja",
    "βιβλίον": "kitab, gulungan",
    "βιβλαρίδιον": "kitab kecil, gulungan kecil",
    "βλάσφημος": "penghujat, penghina",
    "βλαστάνω": "bertunas, bertumbuh",
    "βλασφημέω": "menghujat, menghina (nama)",
    "βλασφημία": "hujat, fitnah",
    "βουλεύω": "berunding, memutuskan",
    "βύσσινος": "dari lenan halus",
    "βύσσος": "lenan halus",
    "γέεννα": "neraka (Gehena)",
    "γένος": "keturunan, bangsa, jenis",
    "γαζοφυλάκιον": "peti persembahan, kotak derma",
    "γινώσκω": "mengetahui, mengenal",
    "γλῶσσα": "lidah; bahasa",
    "γραμματεύς": "ahli Taurat; jurutulis",
    "γραφή": "Kitab Suci, tulisan",
    "γυνή": "perempuan; istri",
    "γῆ": "bumi, tanah",
    "δένδρον": "pohon",
    "δέρω": "memukul, mendera",
    "δέσμιος": "tahanan, orang terpenjara",
    "δίδραχμον": "dua dirham (pajak Bait)",
    "δίκαιος": "benar, adil",
    "δίκτυον": "jala, jaring",
    "δαίμων": "roh jahat, setan",
    "δαιμόνιον": "roh jahat, setan",
    "δερμάτινος": "dari kulit",
    "δεσμωτήριον": "penjara",
    "δεῖπνον": "perjamuan, makan malam",
    "δηνάριον": "dinar (upah sehari)",
    "διάβολος": "Iblis; pemfitnah",
    "διάδημα": "mahkota",
    "διάνοια": "akal budi, pikiran",
    "διακονέω": "melayani",
    "διακονία": "pelayanan",
    "διακρίνω": "membeda-bedakan; bimbang",
    "διαλέγομαι": "berbincang, bertukar pikiran",
    "διασῳζω": "menyelamatkan (dengan selamat)",
    "δικαίωμα": "ketetapan yang benar; perbuatan benar",
    "δικαίως": "dengan benar/adil",
    "δικαίωσις": "pembenaran",
    "δικαιοσύνη": "kebenaran, keadilan",
    "δικαιόω": "membenarkan",
    "διώκω": "mengejar, mengikuti; menganiaya",
    "δοκιμάζω": "menguji, memeriksa",
    "δοκός": "balok (kayu)",
    "δοξάζω": "memuliakan",
    "δουλεία": "perbudakan",
    "δουλεύω": "menghamba, melayani sebagai hamba",
    "δούλη": "hamba perempuan",
    "δοῦλος": "hamba, budak",
    "δράκων": "naga",
    "δρέπανον": "sabit",
    "δυνάστης": "penguasa, pembesar",
    "δυσνόητος": "sukar dimengerti",
    "δόξα": "kemuliaan",
    "δύναμαι": "dapat, mampu, berkuasa",
    "δύναμις": "kuasa, kekuatan; mujizat",
    "δῶρον": "pemberian, persembahan",
    "εἰδωλόθυτον": "makanan persembahan berhala",
    "εἰλικρινής": "murni, tulus",
    "εἰρήνη": "damai, damai sejahtera",
    "εἰρηνοποιός": "pembawa damai",
    "εὐαγγελίζω": "memberitakan Injil, mengabarkan kabar baik",
    "εὐαγγελιστής": "penginjil, pemberita Injil",
    "εὐθύς": "lurus; segera",
    "εὐλάβεια": "takut akan Allah, kesalehan",
    "εὐλαβής": "saleh, takut akan Allah",
    "εὐλογέω": "memberkati",
    "εὐλογία": "berkat",
    "εὐλογητός": "terpuji, yang dipuji",
    "εὐχή": "doa, nazar",
    "ζάω": "hidup",
    "ζητέω": "mencari, menuntut",
    "ζιζάνιον": "lalang",
    "ζυγός": "kuk; timbangan",
    "ζωή": "hidup, kehidupan",
    "ζώνη": "ikat pinggang",
    "ζῆλος": "kecemburuan, iri hati; semangat",
    "ζῳοποιέω": "menghidupkan",
    "ζῷον": "makhluk hidup",
    "θάλπω": "mengasuh, memelihara",
    "θάμβος": "keheranan, takjub",
    "θάνατος": "kematian, maut",
    "θανατόω": "membunuh, menghukum mati",
    "θαρρέω": "berani, tabah",
    "θαρσέω": "beranilah, tabahlah",
    "θαυμάζω": "heran, takjub",
    "θαυμαστός": "ajaib, mengagumkan",
    "θαῦμα": "keajaiban, keheranan",
    "θεμέλιος": "dasar, fondasi",
    "θεοσεβής": "saleh, takut akan Allah",
    "θεράπων": "pelayan, abdi",
    "θεραπεύω": "menyembuhkan",
    "θηρίον": "binatang buas",
    "θησαυρός": "harta; tempat harta",
    "θρόνος": "takhta",
    "θυγάτηρ": "anak perempuan",
    "θυμίαμα": "kemenyan, ukupan",
    "θυσιαστήριον": "mezbah",
    "κάλαμος": "buluh, gelagah; pena",
    "κάμηλος": "unta",
    "κήρυγμα": "pemberitaan, khotbah",
    "καθέδρα": "kursi, tempat duduk",
    "καθαρίζω": "menahirkan, membersihkan",
    "καθαρός": "tahir, bersih, suci",
    "κακία": "kejahatan, kedengkian",
    "κακός": "jahat, buruk",
    "καλέω": "memanggil, menyebut",
    "καλός": "baik, elok",
    "κατάκριμα": "hukuman",
    "κατάκρισις": "penghukuman",
    "κατάπαυσις": "perhentian, peristirahatan",
    "κατακρίνω": "menghukum, menjatuhkan hukuman",
    "καταπέτασμα": "tabir (Bait Suci)",
    "καταρτίζω": "melengkapi, membereskan, memperbaiki",
    "καταφρονέω": "meremehkan, menghina",
    "καταφρονητής": "penghina, pencemooh",
    "κατεξουσιάζω": "memerintah dengan sewenang-wenang",
    "καυχάομαι": "bermegah, memegahkan diri",
    "καύχημα": "kemegahan, kebanggaan",
    "κεντυρίων": "perwira (seratus tentara)",
    "κεραμεύς": "tukang periuk",
    "κηρύσσω": "memberitakan, mengabarkan",
    "κιβωτός": "bahtera; tabut",
    "κιθάρα": "kecapi",
    "κιθαρῳδός": "pemain kecapi",
    "κλάδος": "cabang, ranting",
    "κλείς": "kunci",
    "κληρονομέω": "mewarisi, menerima bagian",
    "κληρονόμος": "ahli waris",
    "κλινίδιον": "tempat tidur kecil, usungan",
    "κλῆρος": "undi; bagian, milik pusaka",
    "κλῆσις": "panggilan",
    "κοίτη": "tempat tidur; percabulan",
    "κοδράντης": "duit (kodran)",
    "κοινωνία": "persekutuan; sumbangan",
    "κοινωνός": "sekutu, teman sekerja",
    "κοινόω": "menajiskan",
    "κράσπεδον": "jumbai, ujung/tepi jubah",
    "κρίνον": "bunga bakung",
    "κρίνω": "menghakimi, mengadili; memutuskan",
    "κρίσις": "penghakiman, hukuman",
    "κραυγή": "teriakan, seruan",
    "κριτής": "hakim",
    "κυνάριον": "anjing (kecil)",
    "κόκκινον": "kain kirmizi (merah)",
    "κόκκος": "biji",
    "κόσμος": "dunia",
    "κόφινος": "bakul, keranjang",
    "κύμινον": "jintan",
    "κύων": "anjing",
    "κώμη": "kampung, desa",
    "κώνωψ": "nyamuk",
    "κῆνσος": "pajak",
    "κῆπος": "taman, kebun",
    "κῆτος": "ikan besar",
    "κῶμος": "pesta pora",
    "λάχανον": "sayuran",
    "λέπρα": "kusta",
    "λέων": "singa",
    "λίβανος": "kemenyan",
    "λαμπάς": "pelita, obor, lampu",
    "λατρεύω": "beribadah, mengabdi (kepada Allah)",
    "λαός": "bangsa, umat",
    "λεγιών": "legiun (pasukan)",
    "λειτουργία": "pelayanan (ibadah), tugas imam",
    "λειτουργός": "pelayan (ibadah), malaikat pelayan",
    "λεπρός": "orang kusta",
    "λεπτός": "peser, uang terkecil",
    "ληνός": "tempat memeras anggur",
    "λιβανωτός": "perukupan, tempat kemenyan",
    "λοιπός": "yang lain, selebihnya; akhirnya",
    "λυτρόω": "menebus",
    "λυχνία": "kaki dian, tempat pelita",
    "λύκος": "serigala",
    "λύτρον": "tebusan",
    "λύτρωσις": "penebusan, pembebasan",
    "λῃστής": "penyamun, perampok",
    "λόγος": "firman; perkataan; perkara, perhitungan",
    "ῥῆμα": "perkataan, firman",
    "μάννα": "manna",
    "μάρτυς": "saksi",
    "μέθη": "kemabukan",
    "μένω": "tinggal, tetap, menanti",
    "μέρος": "bagian; golongan; daerah",
    "μακάριος": "berbahagia",
    "μακαρίζω": "menyebut berbahagia",
    "μακαρισμός": "kebahagiaan",
    "μαρτυρέω": "bersaksi, memberi kesaksian",
    "μαρτυρία": "kesaksian",
    "μαρτύριον": "kesaksian, bukti",
    "μεγαλύνω": "membesarkan, memuliakan",
    "μεσίτης": "pengantara",
    "μεσουράνημα": "puncak langit, tengah langit",
    "μετέχω": "mendapat bagian, turut serta",
    "μετανοέω": "bertobat",
    "μετατίθημι": "memindahkan, mengangkat",
    "μικρός": "kecil, sedikit; muda",
    "μισθός": "upah",
    "μνημεῖον": "kubur, makam",
    "μνᾶ": "mina (satuan uang)",
    "μοιχάομαι": "berzinah",
    "μοιχεύω": "berzinah",
    "μυστήριον": "rahasia",
    "μωρία": "kebodohan",
    "μωραίνω": "menjadi/membuat bodoh, tawar",
    "μωρός": "bodoh",
    "μόδιος": "gantang (takaran)",
    "μύλος": "batu kilangan, gilingan",
    "μύρον": "minyak wangi, narwastu",
    "νέκρωσις": "kematian, kemandulan",
    "νήπιος": "kanak-kanak, bayi",
    "νήφω": "sadar, menguasai diri",
    "ναός": "Bait Suci, tempat kudus",
    "νεκρός": "mati; orang mati",
    "νηστεύω": "berpuasa",
    "νοσσίον": "anak (ayam)",
    "νουθετέω": "menasihati, memperingatkan",
    "νόμισμα": "mata uang",
    "νόμος": "hukum, Taurat",
    "ξύλον": "kayu; tiang, palang",
    "οἰκέτης": "hamba, pelayan rumah",
    "οἰκία": "rumah, keluarga",
    "οἰκοδομή": "bangunan; pembangunan (rohani)",
    "οἰκονομία": "pengurusan, penatalayanan",
    "οἰκονόμος": "bendahara, pengurus rumah",
    "οἰκτίρω": "mengasihani",
    "οἰκτιρμός": "belas kasihan, rahmat",
    "οἶδα": "mengetahui, mengenal",
    "οἶκος": "rumah; keluarga, keturunan",
    "οἶνος": "anggur",
    "οὐράνιος": "sorgawi, dari sorga",
    "πάσχα": "Paskah",
    "πήρα": "kantong, bekal",
    "πίναξ": "pinggan, talam",
    "πίστις": "iman, kepercayaan",
    "παιδίον": "anak kecil",
    "παιδίσκη": "hamba perempuan, dayang",
    "παιδεία": "didikan, ajaran",
    "πανοπλία": "seluruh perlengkapan senjata",
    "παντοκράτωρ": "Yang Mahakuasa",
    "παράβασις": "pelanggaran",
    "παράκλησις": "penghiburan, nasihat, dorongan",
    "παραβαίνω": "melanggar",
    "παραβολή": "perumpamaan",
    "παραγγέλλω": "memerintahkan, berpesan",
    "παραδίδωμι": "menyerahkan, mengkhianati",
    "παραιτέομαι": "menolak, meminta dilepaskan",
    "παρακαλέω": "menghibur, menasihati, memohon",
    "παραμυθέομαι": "menghibur",
    "παρεμβολή": "markas, tangsi; perkemahan",
    "παρθένος": "perawan, anak dara",
    "παροργίζω": "membuat marah, menyakiti hati",
    "παροργισμός": "kemarahan",
    "παροψίς": "pinggan, cawan",
    "παῖς": "anak; hamba",
    "πείθω": "meyakinkan, membujuk; percaya, taat",
    "πειθαρχέω": "menaati",
    "πειράζω": "mencobai, menguji",
    "πειρασμός": "pencobaan",
    "πεντηκοστή": "Pentakosta",
    "περιπατέω": "berjalan, hidup (berkelakuan)",
    "περιστερά": "burung merpati",
    "περιτέμνω": "menyunat",
    "περιτομή": "sunat",
    "πετεινόν": "burung, unggas",
    "πιστός": "setia; dapat dipercaya, beriman",
    "πλεονεξία": "ketamakan, keserakahan",
    "πλοῖον": "perahu, kapal",
    "πλῆθος": "orang banyak, kumpulan besar",
    "ἅγιος": "kudus, suci; orang kudus",
    "ποίμνη": "kawanan domba",
    "ποιμήν": "gembala",
    "ποιμαίνω": "menggembalakan",
    "πολίτης": "warga kota, penduduk",
    "πονηρός": "jahat; si jahat",
    "πορνεία": "percabulan",
    "πορνεύω": "berbuat cabul",
    "πορφύρα": "kain ungu",
    "πραΰς": "lemah lembut",
    "πραιτώριον": "gedung pengadilan, istana wali negeri",
    "πρασιά": "kelompok, jajaran (orang duduk)",
    "πρεσβυτέριον": "majelis tua-tua",
    "πρεσβύτερος": "tua-tua, penatua; yang lebih tua",
    "προεῖπον": "telah berkata dahulu, menubuatkan",
    "προσευχή": "doa; tempat berdoa",
    "προσκυνέω": "menyembah, sujud",
    "προφητεύω": "bernubuat",
    "πρωτότοκος": "anak sulung",
    "πρόβατον": "domba",
    "πτύον": "nyiru, alat penampi",
    "πυνθάνομαι": "bertanya, menyelidiki",
    "πυρόω": "membakar; menyala",
    "πωρόω": "mengeraskan (hati)",
    "πόλις": "kota",
    "πόρνη": "perempuan sundal, pelacur",
    "πύργος": "menara",
    "πῶλος": "keledai muda",
    "σάββατον": "hari Sabat; minggu",
    "σάκκος": "kain kabung",
    "σάλπιγξ": "sangkakala, terompet",
    "σέβομαι": "menyembah, beribadah",
    "σής": "ngengat",
    "σίναπι": "biji sesawi",
    "σαλπίζω": "meniup sangkakala",
    "σαρκικός": "duniawi, bersifat daging",
    "σεμνός": "terhormat, patut dihormati",
    "σεμνότης": "kehormatan, kesopanan",
    "σημεῖον": "tanda, mujizat",
    "σινδών": "kain lenan",
    "σιτιστός": "(ternak) tambun/gemuk",
    "σκάνδαλον": "batu sandungan, penyebab jatuh",
    "σκηνή": "kemah, pondok",
    "σκηνοπηγία": "hari raya Pondok Daun",
    "σκληροκαρδία": "kekerasan hati",
    "σκορπίος": "kalajengking",
    "σμυρνίζω": "mencampur dengan mur",
    "σμύρνα": "mur",
    "σοφίζω": "membuat bijaksana",
    "σοφός": "bijaksana, berhikmat",
    "σπίλος": "noda, cacat",
    "σπιλάς": "noda; karang tersembunyi",
    "σπιλόω": "menodai, mencemarkan",
    "σπυρίς": "bakul, keranjang",
    "σπόγγος": "bunga karang, spons",
    "στάχυς": "bulir (gandum)",
    "στατήρ": "mata uang (empat dirham)",
    "σταυρός": "salib",
    "σταυρόω": "menyalibkan",
    "στενάζω": "mengeluh, berkeluh kesah",
    "στολή": "jubah",
    "στρατηγός": "kepala pengawal, panglima",
    "στρουθίον": "burung pipit",
    "στῦλος": "tiang, soko guru",
    "συγκληρονόμος": "sesama ahli waris",
    "συκῆ": "pohon ara",
    "συνίημι": "mengerti, memahami",
    "συναπόλλυμι": "binasa bersama-sama",
    "συνείδησις": "hati nurani",
    "συσταυροω": "menyalibkan bersama-sama",
    "σφραγίζω": "memeteraikan",
    "σφραγίς": "meterai",
    "σωτήρ": "Juruselamat",
    "σωτήριος": "yang menyelamatkan",
    "σύνδουλος": "sesama hamba",
    "σύνεσις": "pengertian, akal budi",
    "σύσσημον": "tanda (yang disepakati)",
    "σῖτος": "gandum",
    "σῦκον": "buah ara",
    "σῳζω": "menyelamatkan",
    "σῴζω": "menyelamatkan",
    "σῶμα": "tubuh; mayat",
    "τάλαντον": "talenta (satuan uang/berat)",
    "τάφος": "kubur",
    "τέλειος": "sempurna",
    "τέλος": "akhir; pajak, bea",
    "τέρας": "keajaiban, mujizat",
    "τέχνη": "keahlian, keterampilan",
    "ταπεινός": "rendah hati; hina",
    "ταπεινόφρων": "rendah hati",
    "ταῦρος": "lembu jantan",
    "τελώνης": "pemungut cukai",
    "τεῖχος": "tembok",
    "τιμάω": "menghormati, menghargai",
    "τιμή": "hormat; harga, nilai",
    "τρύβλιον": "pinggan, mangkuk",
    "φάτνη": "palungan",
    "φανός": "obor, lampu",
    "φθόνος": "iri hati, dengki",
    "φιάλη": "cawan",
    "φοβέομαι": "takut",
    "φοβέω": "menakuti; (pasif) takut, menghormati",
    "φραγμός": "pagar",
    "φρονίμως": "dengan bijak, cerdik",
    "φρόνιμος": "bijaksana, cerdik",
    "φυλάσσω": "menjaga, memelihara, menuruti",
    "φυλή": "suku, marga",
    "φυτεία": "tanaman",
    "φωτίζω": "menerangi",
    "φόβος": "takut, ketakutan",
    "φύλλον": "daun",
    "φῶς": "terang, cahaya",
    "χάρις": "kasih karunia, anugerah",
    "χάρισμα": "karunia",
    "χαλκός": "tembaga, perunggu; uang tembaga",
    "χαρίζομαι": "mengaruniakan, mengampuni",
    "χιλίαρχος": "kepala pasukan (seribu)",
    "χιτών": "baju dalam, kemeja",
    "χλαμύς": "jubah (tentara)",
    "χοῖρος": "babi",
    "χρηστός": "baik, ramah, murah hati",
    "χρηστότης": "kemurahan, kebaikan",
    "χρυσίον": "emas",
    "χρυσός": "emas",
    "χόρτος": "rumput",
    "χώρα": "daerah, negeri; ladang",
    "ψευδοπροφήτης": "nabi palsu",
    "ψεύδομαι": "berdusta",
    "ἀγάπη": "kasih",
    "ἀγαθοποιέω": "berbuat baik",
    "ἀγαθος": "baik",
    "ἀγαθός": "baik",
    "ἀγαπάω": "mengasihi",
    "ἀγγεῖον": "bejana, wadah",
    "ἀγοράζω": "membeli",
    "ἀδελφή": "saudara perempuan",
    "ἀδελφός": "saudara (laki-laki)",
    "ἀδικέω": "berbuat tidak adil, menganiaya",
    "ἀδικία": "ketidakadilan, kejahatan",
    "ἀετός": "burung nasar, rajawali",
    "ἀκέραιος": "tulus, tak bercela",
    "ἀκαθαρσία": "kenajisan",
    "ἀκρίς": "belalang",
    "ἀλάβαστρον": "buli-buli pualam",
    "ἀλάβαστρος": "buli-buli pualam",
    "ἀλέκτωρ": "ayam jantan",
    "ἀλήθεια": "kebenaran",
    "ἀλείφω": "mengurapi, meminyaki",
    "ἀληθής": "benar, sejati",
    "ἀληθινός": "benar, sejati",
    "ἀληθῶς": "sungguh, sebenarnya",
    "ἀμέμπτως": "tanpa cela",
    "ἀμίαντος": "tak bernoda, tak tercemar",
    "ἀμπελουργός": "pengurus/tukang kebun anggur",
    "ἀμώμητος": "tak bercacat",
    "ἀνάστασις": "kebangkitan",
    "ἀνέγκλητος": "tak bercela, tak bersalah",
    "ἀνεπίλημπτος": "tak bercela",
    "ἀνθρώπινος": "manusiawi, bersifat manusia",
    "ἀνομία": "kedurhakaan, pelanggaran hukum",
    "ἀντίχριστος": "antikristus",
    "ἀνόητος": "bodoh, tak berakal",
    "ἀξίνη": "kapak",
    "ἀξίως": "dengan layak/patut",
    "ἀπείθεια": "ketidaktaatan",
    "ἀπειθέω": "tidak taat, tidak percaya",
    "ἀπειθής": "tidak taat, durhaka",
    "ἀπιστία": "ketidakpercayaan",
    "ἀποδίδωμι": "membayar, mengembalikan, memberi",
    "ἀποδοκιμάζω": "menolak, membuang",
    "ἀποθήκη": "lumbung",
    "ἀποκάλυψις": "penyataan, wahyu",
    "ἀποκαλύπτω": "menyatakan, menyingkapkan",
    "ἀπολύω": "melepaskan, membebaskan; menceraikan",
    "ἀποστολή": "kerasulan",
    "ἀπρόσκοπος": "tak bercela, tak tersandung",
    "ἀπόλλυμι": "membinasakan; binasa, hilang",
    "ἀπόστολος": "rasul, utusan",
    "ἀπώλεια": "kebinasaan, kehancuran",
    "ἀργός": "malas, sia-sia",
    "ἀργύριον": "perak, uang perak",
    "ἀρνίον": "anak domba",
    "ἀρχή": "permulaan; pemerintah, penguasa",
    "ἀρχιερατικός": "keimaman besar",
    "ἀρχιερεύς": "imam besar; imam kepala",
    "ἀρχισυναγωγος": "kepala rumah ibadat",
    "ἀσέβεια": "kefasikan, kedurhakaan",
    "ἀσέλγεια": "hawa nafsu, perbuatan cabul",
    "ἀσεβέω": "berbuat fasik",
    "ἀσεβής": "fasik, durhaka",
    "ἀσκός": "kirbat (kantong kulit anggur)",
    "ἀσπάζομαι": "memberi salam",
    "ἀσσάριον": "duit (asarion)",
    "ἀσωτία": "hidup berfoya-foya, pemborosan",
    "ἀσύνετος": "tak berakal, bebal",
    "ἀφίημι": "membiarkan, meninggalkan; mengampuni",
    "ἁγιάζω": "menguduskan",
    "ἁγιασμός": "pengudusan, kekudusan",
    "ἁμάρτημα": "dosa",
    "ἁμαρτάνω": "berdosa",
    "ἁμαρτία": "dosa",
    "ἁμαρτωλός": "orang berdosa",
    "ἁπλοῦς": "tulus, murni",
    "ἁπλότης": "ketulusan, kemurahan hati",
    "ἁπλῶς": "dengan tulus/murah hati",
    "ἄβυσσος": "jurang maut, lubang tak terduga",
    "ἄγγελος": "malaikat; utusan",
    "ἄγκιστρον": "kail",
    "ἄγω": "membawa, memimpin; pergi",
    "ἄδικος": "tidak adil, orang lalim",
    "ἄκανθα": "semak duri, onak",
    "ἄλογος": "tak berakal (binatang)",
    "ἄμεμπτος": "tak bercela",
    "ἄμπελος": "pohon anggur",
    "ἄμωμος": "tak bercacat, tak bernoda",
    "ἄνηθον": "adas",
    "ἄνθος": "bunga",
    "ἄνομος": "durhaka, tanpa hukum",
    "ἄπιστος": "tidak percaya",
    "ἄπταιστος": "tak tersandung, tak jatuh",
    "ἄργυρος": "perak",
    "ἄρτος": "roti",
    "ἄρχων": "pemimpin, penguasa, pemuka",
    "ἄρωμα": "rempah-rempah wangi",
    "ἄσπιλος": "tak bernoda, tak bercacat",
    "ἄφεσις": "pengampunan, pembebasan",
    "ἄφρων": "bodoh, tak berakal",
    "ἄχυρον": "sekam, jerami",
    "ἅλων": "tempat pengirikan",
    "ἐθνικός": "orang yang tak mengenal Allah, kafir",
    "ἐκδικέω": "membalas, menuntut keadilan",
    "ἐκκλησία": "jemaat, gereja; perkumpulan",
    "ἐκλεκτός": "pilihan, yang terpilih",
    "ἐκπειράζω": "mencobai",
    "ἐλάχιστος": "yang terkecil, paling hina",
    "ἐλέγχω": "menyatakan/menegur kesalahan, membuktikan",
    "ἐλεάω": "mengasihani",
    "ἐλπίζω": "berharap",
    "ἐλπίς": "harapan, pengharapan",
    "ἐμπαίζω": "mengolok-olok, mempermainkan",
    "ἐμπαίκτης": "pengejek, pengolok",
    "ἐμπεριπατέω": "berjalan di antara, hidup di tengah",
    "ἐντέλλομαι": "memerintahkan, berpesan",
    "ἐντολή": "perintah, hukum",
    "ἐξετάζω": "menyelidiki, memeriksa dengan teliti",
    "ἐξομολογέω": "mengaku, memuji, bersyukur",
    "ἐξουσιάζω": "berkuasa atas, memerintah",
    "ἐπίβλημα": "kain penambal, tambalan",
    "ἐπαγγελία": "janji",
    "ἐπιγινώσκω": "mengenal, memahami benar",
    "ἐπιεικής": "ramah, baik hati, murah hati",
    "ἐπιμένω": "bertahan, tetap tinggal",
    "ἐπιστήμων": "berpengetahuan, cakap",
    "ἐπιτιμάω": "menegur, menghardik",
    "ἐπουράνιος": "sorgawi, di sorga",
    "ἐρημία": "padang gurun, tempat sunyi",
    "ἐρημόω": "membinasakan, menyunyikan",
    "ἐριθεία": "mementingkan diri, perselisihan",
    "ἐρωτάω": "bertanya; meminta",
    "ἐχθρός": "musuh, seteru",
    "ἑκατοντάρχης": "perwira (kepala seratus)",
    "ἑορτή": "hari raya, perayaan",
    "ἔγερσις": "kebangkitan",
    "ἔθνος": "bangsa; bangsa-bangsa bukan Yahudi",
    "ἔλαιον": "minyak (zaitun)",
    "ἔνδυμα": "pakaian",
    "ἔνταλμα": "perintah, peraturan",
    "ἔξεστι": "boleh, diperbolehkan",
    "ἔπαινος": "pujian",
    "ἔργον": "pekerjaan, perbuatan",
    "ἔρημος": "padang gurun, tempat sunyi",
    "ἔρις": "perselisihan, pertengkaran",
    "ἔριφος": "kambing",
    "ἔχιδνα": "ular berbisa, ular beludak",
    "ἡγεμών": "gubernur, wali negeri; pemimpin",
    "ἡδύοσμον": "selasih, tanaman rempah",
    "ἰχθύδιον": "ikan kecil",
    "ἰχθύς": "ikan",
    "ἱεράτευμα": "keimaman, para imam",
    "ἱερατεία": "jabatan imam",
    "ἱερεύς": "imam",
    "ἱερωσύνη": "jabatan imam, keimaman",
    "ἱερόν": "Bait Suci",
    "ἱερός": "kudus, suci; Bait Suci",
    "ἱλασμός": "pendamaian, korban pendamaian",
    "ἱμάς": "tali (kasut)",
    "ἵππος": "kuda",
    "ὀθόνη": "kain lebar (lenan)",
    "ὀθόνιον": "kain kafan (lenan)",
    "ὀλιγοπιστος": "kurang percaya",
    "ὀμνύω": "bersumpah",
    "ὀφείλημα": "utang; kesalahan",
    "ὀφείλω": "berutang, wajib",
    "ὀφειλέτης": "orang berutang, orang bersalah",
    "ὁμοίωμα": "rupa, keserupaan, gambar",
    "ὁμοίωσις": "rupa, keserupaan",
    "ὁμοιότης": "kesamaan, keserupaan",
    "ὄνομα": "nama",
    "ὄνος": "keledai",
    "ὄξος": "anggur asam, cuka",
    "ὄρνεον": "burung",
    "ὄρνις": "induk ayam, unggas",
    "ὄφις": "ular",
    "ὅπλον": "senjata, perlengkapan",
    "ὅρκος": "sumpah",
    "ὑάλινος": "dari kaca",
    "ὑπακούω": "menaati, mendengarkan",
    "ὑπηρέτης": "pelayan, hamba, pengawal",
    "ὑποζύγιον": "keledai (hewan beban)",
    "ὑποκριτής": "orang munafik",
    "ὑπομένω": "bertahan, tabah",
    "ὑποτάσσω": "menaklukkan, menundukkan",
    "ὑποταγή": "ketaatan, ketundukan",
    "ὑπόκρισις": "kemunafikan",
    "ὕαλος": "kaca",
    "ὕψιστος": "Yang Mahatinggi",
    "ὡσαννά": "Hosana",
    "ᾅδης": "dunia orang mati, alam maut",
    "ῥάβδος": "tongkat, gada",
    "ῥάκος": "kain (koyak), secarik kain",
    "ῥίζα": "akar",
    "ῥαφίς": "jarum",

    # phrase-lemmas
    "εἰς αἰῶνα, εἰς τὸν αἰῶνα, εἰς τοὺς αἰῶνας, εἰς ἡμέραν αἰῶνος, εἰς τοὺς αἰῶνας τῶν αἰώνων, εἰς τὸν αἰῶνα τοῦ αἰῶνος, εἰς αἰῶνας αἰώνων, εἰς πάντας τοῦ αἰῶνας, τοῦ αἰῶνος τῶν αἰώνων": "selama-lamanya, kekal",
    "συντελεία αἰῶνός, συντελεία τοῦ αἰῶνος": "akhir zaman",
    "τὸ βδέλυγμα τῆς ἐρημώσεως": "pembinasa keji",
    "υἱος τοῦ ἀνθρώπου": "Anak Manusia",
    "πνευμα ἁγιον": "Roh Kudus",
    "πνευμα ἀκαθαρτος": "roh najis",
    "οἰκος τοῦ θεοῦ": "rumah Allah",
    "λαμπάς, λύχνος": "pelita, lampu",
    "οἶνος νέος": "anggur baru",
    "σκοτος τὸ ἐξώτερον": "kegelapan yang paling gelap (di luar)",
    "πονηρος": "jahat; si jahat",
    "Δαυίδ": "Daud",
}

GK.update({
    "αἰνέω": "memuji",
    "αἰτέω": "meminta, memohon",
    "αἶνος": "pujian",
    "αἷμα": "darah",
    "γνῶσις": "pengetahuan, pengenalan",
    "δέομαι": "memohon, berdoa",
    "δαιμονίζομαι": "kerasukan setan",
    "διάκονος": "pelayan, diaken",
    "διενθυμέομαι": "memikirkan, merenungkan",
    "διωγμός": "penganiayaan",
    "δουλόω": "memperbudak, memperhamba",
    "δραχμή": "dirham (keping perak)",
    "δόλος": "tipu daya, muslihat",
    "εἰδωλολάτρης": "penyembah berhala",
    "εἰδωλολατρία": "penyembahan berhala",
    "εἰκών": "gambar, rupa",
    "εὐσέβεια": "kesalehan, ibadah",
    "εὐχαριστέω": "mengucap syukur",
    "θάρσος": "keberanian",
    "θλῖψις": "kesengsaraan, penderitaan",
    "θυγάτριον": "anak perempuan (kecil)",
    "θυμός": "amarah, geram",
    "θυσία": "korban, persembahan",
    "θύρα": "pintu",
    "καρδία": "hati",
    "καταλλαγή": "pendamaian, perdamaian",
    "κατασκηνόω": "bersarang, berdiam",
    "κατευλογέω": "memberkati",
    "κλίνη": "tempat tidur, ranjang",
    "κληρονομία": "warisan, milik pusaka",
    "κλητός": "yang terpanggil",
    "κράζω": "berteriak, berseru",
    "κρίμα": "hukuman, keputusan hakim",
    "κραυγάζω": "berteriak, berseru",
    "μαθητής": "murid",
    "μεγαλωσύνη": "kebesaran, keagungan",
    "μετάνοια": "pertobatan",
    "μεταμέλομαι": "menyesal",
    "νεκρόω": "mematikan",
    "οἰκτίρμων": "penuh belas kasihan",
    "οἰνοφλυγία": "kemabukan, pesta anggur",
    "πάθημα": "penderitaan, sengsara",
    "πάθος": "hawa nafsu",
    "παράπτωμα": "pelanggaran, dosa",
    "παραγγελία": "perintah, pesan",
    "πιστεύω": "percaya, beriman",
    "πλησίον": "sesama, tetangga",
    "πνευματικός": "rohani, bersifat roh",
    "πονηρία": "kejahatan",
    "πραΰτης": "kelemahlembutan",
    "πρεσβεία": "utusan, kedutaan",
    "πρεσβεύω": "menjadi utusan",
    "πρεσβύτης": "orang tua, orang yang lanjut usia",
    "προσεύχομαι": "berdoa",
    "προφήτης": "nabi",
    "προφητικός": "kenabian",
    "πρωτοτόκια": "hak kesulungan",
    "πρόσκομμα": "batu sandungan",
    "πυλών": "pintu gerbang",
    "πόρνος": "orang cabul",
    "σάρκινος": "bersifat daging, duniawi",
    "σκανδαλίζω": "menyesatkan, membuat tersandung",
    "σκότος": "kegelapan",
    "σοφία": "hikmat, kebijaksanaan",
    "σπεῖρα": "pasukan, batalion",
    "σπλαγχνίζομαι": "tergerak oleh belas kasihan",
    "στέφανος": "mahkota",
    "στενοχωρέω": "mengalami kesesakan",
    "στενοχωρία": "kesesakan, kesukaran",
    "συγχαίρω": "turut bersukacita",
    "συμμέτοχος": "sekutu, peserta",
    "συναγωγή": "rumah ibadat, sinagoge",
    "συνετός": "berakal budi, bijaksana",
    "τάξις": "aturan, tata tertib, golongan",
    "τίμιος": "berharga, mulia",
    "ταπείνωσις": "kerendahan, kehinaan",
    "ταπεινοφροσύνη": "kerendahan hati",
    "ταπεινόω": "merendahkan (diri)",
    "τελειόω": "menyempurnakan, menyelesaikan",
    "τεχνίτης": "tukang, ahli, seniman",
    "τρέχω": "berlari",
    "φθονέω": "iri hati, dengki",
    "φιλέω": "mengasihi, menyayangi",
    "φοβερός": "menakutkan, dahsyat",
    "φυσίωσις": "kesombongan",
    "φυσιόω": "menyombongkan diri, membesarkan diri",
    "φύσις": "kodrat, sifat alami",
    "χαίρω": "bersukacita; salam",
    "χαρά": "sukacita",
    "ψυχή": "jiwa, nyawa",
    "ἀββά": "Abba (Bapa)",
    "ἀγαπητός": "yang dikasihi, kekasih",
    "ἀληθεύω": "berkata benar, jujur",
    "ἀμπελών": "kebun anggur",
    "ἀπαρχή": "buah sulung, hasil pertama",
    "ἀποκαταλλάσσω": "mendamaikan (sepenuhnya)",
    "ἀπολύτρωσις": "penebusan, pembebasan",
    "ἐλεέω": "mengasihani",
    "ἐξαγοράζω": "menebus, memanfaatkan",
    "ἐξουσία": "kuasa, wewenang",
    "ἐπίγνωσις": "pengenalan (yang benar)",
    "ἐπαγγέλλομαι": "menjanjikan",
    "ἐπαινέω": "memuji",
    "ἐπερωτάω": "bertanya",
    "ἐπιθυμέω": "menginginkan, mengingini",
    "ἐπιπλήσσω": "menegur keras",
    "ἑδραῖος": "teguh, kokoh",
    "ἔλεος": "belas kasihan, rahmat",
    "ὀργή": "murka, amarah",
    "ὑδρία": "tempayan, buyung air",
    "ὑπακοή": "ketaatan",
    "ὑπομονή": "ketekunan, ketabahan",
    "ὑποπόδιον": "tumpuan kaki",
    "ὑπόδημα": "kasut, sandal",
})

# --- Añadido en la curación de Tonsawang (tnw): lemas con rendering del equipo
# --- pero sin glosa. Significado léxico estándar del griego, no del vernáculo.
GK.update({
    # nombres propios y gentilicios
    "Αἰγύπτιος": "orang Mesir",
    "Αἰθίοψ": "orang Etiopia",
    "Ἀθηναῖος": "orang Atena",
    "Ἀθῆναι": "Atena",
    "Ἄραψ": "orang Arab",
    "Ἁριμαθαία": "Arimatea",
    "Βέροια": "Berea",
    "Βεελζεβούλ": "Beelzebul (penghulu setan)",
    "Βηθλέεμ": "Betlehem",
    "Γαλιλαία-1": "Galilea",
    "Γαλιλαῖος": "orang Galilea",
    "Γερασηνός": "orang Gerasa",
    "Ζαχαρίας-1": "Zakharia",
    "Θεόφιλος": "Teofilus",
    "Ἰουδαῖος-1": "Yahudi, orang Yahudi",
    "Ἰουδαῖος-2": "orang Yahudi",
    "Ἰσραηλίτης": "orang Israel",
    "Κρής": "orang Kreta",
    "Λευίτης": "orang Lewi",
    "Ναζαρηνός": "orang Nazaret",
    "Ναζωραῖος": "orang Nazaret",
    "Νινευίτης": "orang Niniwe",
    "Παῦλος-1": "Paulus",
    "Ῥωμαῖος": "orang Roma, warga negara Roma",
    "Σαδδουκαῖος": "orang Saduki",
    "Σαλαθιήλ": "Sealtiel",
    "Σαμαρίτης": "orang Samaria",
    "Σαμουήλ": "Samuel",
    "Συρία": "Siria",
    "Σύρος": "orang Siria",
    "Φαρισαῖος": "orang Farisi",

    # sustantivos, verbos y locuciones
    "ἀγαθοεργέω": "berbuat baik",
    "ἀγοραῖος": "orang pasar; hari sidang pengadilan",
    "ἁγνίζω": "menyucikan diri, mentahirkan",
    "ἀδίκημα": "perbuatan salah, kejahatan",
    "ἀθέμιτος": "terlarang, tidak patut menurut hukum",
    "ἀλίσγημα": "pencemaran, kenajisan",
    "ἀλλόφυλος": "orang dari bangsa lain, orang asing",
    "ἅλυσις": "rantai",
    "ἀλώπηξ": "rubah",
    "ἀμήν": "amin; sesungguhnya",
    "ἀνάγαιον": "ruang atas",
    "ἀναβαθμός": "tangga",
    "ἀνακρίνω": "memeriksa, menyelidiki, mengadili",
    "ἀπ᾽ αἰῶνος, (ἀπὸ) τῶν αἰώνων, ἐκ τοῦ αἰῶνος": "sejak dahulu kala, dari zaman purbakala",
    "ἀπαλλάσσω": "melepaskan, membebaskan; berdamai (menyelesaikan perkara)",
    "ἀπιστέω": "tidak percaya",
    "ἀπογραφή": "pendaftaran, sensus",
    "ἀπογράφω": "mendaftarkan (untuk sensus)",
    "ἀρήν": "anak domba",
    "ἅρμα": "kereta",
    "ἄροτρον": "bajak",
    "ἀρχιτελώνης": "kepala pemungut cukai",
    "ἀσφάλεια": "kepastian, keamanan",
    "ἀσφαλής": "pasti, teguh, aman",
    "ἀσφαλως": "dengan pasti; dengan aman",
    "βάτος": "semak duri; bat (takaran cairan)",
    "βαλλάντιον": "pundi-pundi, dompet uang",
    "βασίλειον": "istana raja",
    "βδέλυγμα": "kekejian, sesuatu yang menjijikkan",
    "βελόνη": "jarum",
    "βίος-1": "harta, kekayaan, nafkah",
    "βίος-2": "hidup, kehidupan",
    "βίος-3": "cara hidup, perilaku",
    "βιωτικός": "yang berkaitan dengan hidup sehari-hari, duniawi",
    "βοῦς": "sapi, lembu",
    "βυρσεύς": "penyamak kulit",
    "βῆμα": "kursi pengadilan, tempat pengadilan",
    "γλεῦκος": "anggur manis (yang baru)",
    "γράφω": "menulis",
    "δακτύλιος": "cincin",
    "δέησις": "permohonan, doa",
    "δεσμός": "belenggu, ikatan; penjara",
    "διαθήκη": "perjanjian; wasiat",
    "διακαθαίρω": "membersihkan sampai tuntas",
    "διαμαρτύρομαι": "bersaksi dengan sungguh-sungguh, memperingatkan dengan tegas",
    "διαφυλάσσω": "menjaga, melindungi",
    "δῶμα": "atap rumah",
    "ἐγείρω": "membangunkan, membangkitkan; bangun",
    "εἰσφερω": "membawa masuk",
    "εἶπον": "berkata, mengatakan",
    "ἐκδίκησις": "pembalasan, penghukuman; pembelaan hak",
    "ἐκλέγω": "memilih",
    "ἐλαία-1": "pohon zaitun",
    "ἐλαιών": "kebun zaitun, Bukit Zaitun",
    "ἔνδοξος": "mulia, terhormat; gemilang",
    "ἔννομος": "menurut hukum, sah",
    "ἔξεστι(ν)-1": "boleh, diperbolehkan (menurut hukum)",
    "ἔξεστι(ν)-2": "boleh, diperbolehkan (menurut hukum)",
    "ἔπαυλις": "tempat tinggal, perkampungan",
    "ἐπικαλέω": "memanggil, menyebut; berseru kepada",
    "ἐπικρίνω": "memutuskan, menjatuhkan keputusan",
    "ἐπισκοπή": "jabatan penilik; kunjungan (Allah)",
    "ἐσθής": "pakaian, jubah",
    "εὐαγγέλιον": "kabar baik, Injil",
    "ζῳογονέω": "memelihara hidup, menghidupkan",
    "θέατρον": "teater, gedung pertunjukan; tontonan",
    "θεά": "dewi",
    "θεμέλιον": "dasar, fondasi",
    "θεραπεία": "penyembuhan; para pelayan rumah tangga",
    "θύω": "menyembelih, mengurbankan",
    "ἱερατεύω": "melayani sebagai imam",
    "ἱλάσκομαι": "mengadakan pendamaian; berbelas kasihan (mengampuni)",
    "ἱμάτιον-1": "jubah, pakaian luar",
    "ἱμάτιον-2": "pakaian, baju",
    "ἱματισμός": "pakaian",
    "ἰσχύω-1": "sanggup, mampu",
    "ἰσχύω-3": "kuat, berdaya",
    "καθαρισμός": "penyucian, pentahiran",
    "καλος": "baik, elok, indah",
    "κάρφος": "selumbar, serpihan kayu",
    "καρδιογνώστης": "yang mengenal hati manusia",
    "κατάλυμα-1": "penginapan, tempat menumpang",
    "κατάλυμα-2": "ruang perjamuan, bilik tamu",
    "καταδικάζω": "menghukum, menjatuhkan hukuman",
    "κατασκήνωσις": "sarang, tempat bersarang",
    "κενός": "kosong; sia-sia, hampa",
    "κέραμος": "genteng, ubin atap",
    "κεράμιον": "kendi, buyung tanah liat",
    "κεράτιον": "buah polong (makanan babi)",
    "κλίβανος": "tungku, perapian",
    "κοινός-1": "bersama, milik bersama",
    "κόραξ": "burung gagak",
    "κτήνος": "hewan ternak, binatang tunggangan",
    "λεπτόν": "lepta (uang tembaga kecil)",
    "λύχνος": "pelita, lampu",
    "μεγαλεῖον": "perbuatan besar (Allah), kebesaran",
    "μεριστης": "pembagi (warisan), penengah",
    "μέτοχος": "teman sekutu, kawan seperserikatan",
    "μίσθιος": "orang upahan, pekerja upahan",
    "μνηστεύω": "bertunangan, dipertunangkan",
    "μνῆμα": "kuburan, makam",
    "μοιχός": "pezina (laki-laki)",
    "μόσχος": "anak lembu, lembu muda",
    "νηστεία": "puasa",
    "νομικός": "ahli Taurat",
    "νομοδιδάσκαλος": "guru hukum Taurat",
    "νοσσιά": "anak-anak burung",
    "νυμφών": "kamar pengantin; pesta pernikahan",
    "ὀικέτης": "hamba rumah tangga, pelayan",
    "οἰκουμένη": "dunia yang berpenduduk, seluruh dunia",
    "ὅσιος-1": "kudus, saleh",
    "ὁσιότης": "kesalehan, kekudusan",
    "οὐαί": "celaka!",
    "παγίς": "jerat, perangkap",
    "πανδοχεύς": "pemilik penginapan",
    "πανδοχεῖον": "penginapan",
    "παρατήρησις": "pengamatan, tanda yang dapat diamati",
    "πατήρ": "bapa, ayah",
    "πέδη": "belenggu kaki",
    "πήγανον": "inggu (tanaman rempah)",
    "πινακίδιον": "batu tulis, papan tulis kecil",
    "πληρόω-2": "menggenapi, memenuhi",
    "πνεῦμα ἅγιον": "Roh Kudus",
    "ποίμνιον": "kawanan domba",
    "προσήλυτος": "proselit, penganut agama Yahudi dari bangsa lain",
    "προσφέρω": "membawa kepada, mempersembahkan",
    "προφῆτις": "nabi perempuan",
    "πτερύγιον": "bubungan, puncak (bait Allah)",
    "ῥύομαι": "melepaskan, menyelamatkan",
    "σαββάτου ὁδός": "perjalanan sehari Sabat",
    "σίκερα": "minuman keras",
    "σκάφη": "sekoci, perahu kecil",
    "σορός": "usungan mayat, peti mayat",
    "σουδάριον": "sapu tangan, kain penutup muka",
    "σπλάγχνον": "isi perut; belas kasihan yang dalam",
    "σπουδή-1": "ketergesaan, kesegeraan; kesungguhan",
    "στέγη": "atap",
    "συκάμινος": "pohon ara hutan, pohon murbei",
    "σωματικός": "berwujud tubuh, jasmani",
    "σωτήριον": "keselamatan (dari Allah)",
    "ταμεῖον-1": "kamar, bilik dalam",
    "ταμεῖον-2": "gudang, lumbung",
    "τελώνιον": "rumah cukai, tempat pemungutan pajak",
    "τρῆμα": "lubang (jarum)",
    "τρυγών": "burung tekukur",
    "υἱὸς τοῦ ἀνθρώπου": "Anak Manusia",
    "υἱὸς τοῦ θεοῦ": "Anak Allah",
    "ὑπερῷον": "ruang atas",
    "ὑποκρίνομαι": "berpura-pura, berlagak",
    "ὕψος": "ketinggian, tempat tinggi",
    "φίλος": "sahabat, teman",
    "φιλάργυρος": "cinta uang, tamak",
    "φόβητρον": "hal yang mengerikan, kejadian yang menakutkan",
    "φυλακή-1": "penjara",
    "φυλακή-3": "giliran jaga (malam), waktu berjaga",
    "φυλάσσω φυλακάς": "berjaga-jaga pada giliran jaga",
    "χάραξ": "kubu pengepungan, benteng bertiang",
    "χαριτόω": "mengaruniai kasih karunia",
    "χρῆμα": "uang, harta benda",
    "χρίω": "mengurapi",
})

HB = {
    "יהוה": "TUHAN (YHWH)",
    "אהב": "mengasihi, kasih",
    "דְּבַר־יהוה": "firman TUHAN",
    "דָּג, דָּגָה": "ikan",
    "דָּוִד": "Daud",
    "זֶבַח": "korban sembelihan",
    "חֶסֶד": "kasih setia",
    "חַטָּאת": "dosa; korban penghapus dosa",
    "יִרְאָה": "takut (akan Allah), hormat",
    "ירא": "takut, menghormati (Allah)",
    "כִּסֵּא": "takhta, kursi",
    "מִנְחָה": "korban sajian, persembahan",
    "מַטֶּה": "tongkat; suku",
    "עִיר": "kota",
    "עֵדוּת": "kesaksian, peraturan (loh hukum)",
    "עֹלָה": "korban bakaran",
    "שַׂר": "pembesar, panglima, pemimpin",
    "שׁבע": "bersumpah",
    "מֶלֶךְ": "raja; kerajaan",
}


# --------------------------------------------------------------------------
# Lemas con rendering del equipo que no tenían glosa (detectados en Tombulu).
# Glosas tomadas de BiblicalTermsId.xml (localización indonesia de Paratext),
# recortadas a las acepciones cortas; las ausentes de esa lista, escritas a mano.
# --------------------------------------------------------------------------

GK.update({
    "Βεροιαῖος": "orang Berea",
    "Γαλάτης": "orang Galatia",
    "Καῖσαρ": "Kaisar",
    "Λαοδικεύς": "orang Laodikia",
    "Σαμαρῖτις": "perempuan Samaria",
    "Σιδώνιος-1": "orang Sidon",
    "Σινᾶ": "gunung Sinai",
    "Σκύθης": "orang Skit",
    "Φαραώ": "Firaun",
    "Φιλιππήσιος": "orang Filipi",
    "Χερούβ": "kerub",
    "Χριστιανός": "yang Kristen",
    "αἱματεκχυσία": "penumpahan darah",
    "αἴγειος": "(dari) kambing",
    "αὐθεντέω": "memerintah",
    "βέβηλος": "omongan kosong, (orang) duniawi, takhayul",
    "βέλος": "panah",
    "βίος": "hidup, kehidupan; nafkah",
    "βοηθέω": "menolong",
    "βούλομαι": "menghendaki, ingin",
    "βροντή": "guruh, guntur",
    "βωμός": "mezbah",
    "γεννάω": "memperanakkan, melahirkan",
    "γονυπετέω": "berlutut",
    "γράμμα": "tulisan, huruf, Kitab",
    "δέρμα": "kulit",
    "δίλογος": "bercabang lidah",
    "δεσπότης": "tuan, penguasa",
    "διακαθαριζω": "membersihkan sama sekali",
    "διαλλάσσω": "berdamai",
    "εἰδωλεῖον": "kuil",
    "εἰδωλολατρια": "penyembahan berhala",
    "εἰρηνεύω": "hidup berdamai, hidup dalam damai sejahtera",
    "εἰς Χριστὸν, ἐν Χριστῷ": "dalam Kristus",
    "εἴδωλον": "berhala",
    "εὐθύτης": "benar, dari kebenaran",
    "εὐχη": "doa",
    "εὔχομαι": "berharap, berdoa",
    "θήρα": "jerat",
    "θεμελιόω": "berdasar, meletakkan dasar",
    "θρέμμα": "ternak",
    "θυμιατήριον": "mezbah ukupan, pedupaan",
    "θυρίς": "jendela, tingkap",
    "θυρεός": "perisai",
    "θυρωρός": "penunggu pintu, penjaga pintu",
    "κάλυμμα": "selubung",
    "κάμινος": "dapur api, tungku, persetujuan",
    "κέρμα": "uang, uang penukaran",
    "καθαρότης": "ketahiran, kesucian",
    "κλῆμα": "ranting",
    "κολυμβήθρα": "kolam (untuk mandi)",
    "κοσμοκράτωρ": "penghulu-penghulu dunia",
    "κρίθινος": "dari jelai",
    "λέντιον": "kain, handuk",
    "λειτουργικός": "melayani",
    "λυτρωτής": "penyelamat",
    "λόγχη": "tombak",
    "μισθωτός": "orang upahan",
    "μοιχαλίς": "perempuan berzina",
    "μοιχαλίς-1": "wanita yang berzinah",
    "μοιχεία": "perzinahan",
    "νάρδος": "narwastu",
    "ναῦς": "kapal",
    "νιπτήρ": "basi, baskom",
    "οἰκειος": "kawan-kawan, anggota keluarga",
    "οὖς": "telinga",
    "πάλιν": "lagi, kembali",
    "παλαιός": "lama, tua",
    "παλιγγενεσία": "penciptaan kembali, Dunia yang Baru",
    "πανταχοῦ": "di mana-mana",
    "παραδοσις": "adat istiadat",
    "παραλυτικός": "orang lumpuh",
    "παρατηρέω": "mengamat-amati, mengintai",
    "περικεφαλαία": "ketopong",
    "πιστικός": "murni",
    "πλοιάριον": "perahu (kecil)",
    "πνευματικῶς": "secara rohani",
    "προσάββατον": "hari persiapan (sebelum Sabat)",
    "προσαγωγή": "jalan masuk",
    "προσκεφάλαιον": "tilam, bantal",
    "προσκόπτω": "tersandung, terantuk",
    "προσφάγιον": "lauk-pauk, ikan",
    "πύθων": "(roh) tenung",
    "πῦρ τὸ αἰώνιον": "api kekal, api neraka",
    "σαββατισμός": "istirahat Sabat",
    "σαγήνη": "pukat, jala",
    "σανδάλιον": "alas kaki, sepatu",
    "σαργάνη": "keranjang",
    "σειρά": "rantai, tali",
    "σιρικόν": "sutera",
    "σκευή": "alat-alat, perkakas-perkakas",
    "σκηνοποιός": "tukang kemah",
    "σκηνόω": "mendirikan kemah (tinggal, berdiam)",
    "σκύβαλον": "sampah",
    "στάμνος": "buli, belanga",
    "στίγμα": "tanda-tanda",
    "στεφανόω": "memahkotai",
    "στοά": "serambi",
    "συκομορέα": "pohon ara",
    "σχοινίον": "tali",
    "σχολή": "ruang kuliah",
    "σύζυγος": "Sunsugos",
    "τρίστεγον": "tingkat tiga",
    "τόξον": "busur, panah",
    "φάντασμα": "hantu",
    "φοῖνιξ": "pohon palem",
    "φραγέλλιον": "cambuk",
    "φρονέω": "memikirkan, berpikir",
    "φυλακτήριον": "tali sembahyang",
    "φόρος": "pajak",
    "χαλινός": "kekang",
    "χαλκίον": "perkakas tembaga",
    "χερούβ": "kerub",
    "χρυσοδακτύλιος": "pakai cincin emas",
    "ψευδόχριστος": "mesias palsu",
    "ἀΐδιος": "kekal",
    "ἀγαθοποιός": "orang yang bekerja dengan baik",
    "ἀγαθουργεω": "lakukan baik",
    "ἀγαθωσύνη": "kebaikan",
    "ἀγαλλίασις": "kegirangan, sukacita besar",
    "ἀγαλλιάω": "bersukacita, bergembira",
    "ἀγανακτέω": "marah, gusar",
    "ἀγγαρεύω": "memaksa (memikul beban)",
    "ἀγρός": "ladang; desa",
    "ἀδελφότης": "persaudaraan, saudara-saudara",
    "ἀδύνατος": "tidak mungkin; lemah",
    "ἀκροβυστία": "orang-orang tak bersunat",
    "ἀκρογωνιαῖος": "batu penjuru, batu yang dipilih, batu yang terutama",
    "ἀλόη": "minyak gaharu",
    "ἀμέμπτος": "tanpa cela, tidak bersalah",
    "ἀμεταμέλητος": "yang tidak akan disesalkan, yang tidak akan ditarik kembali",
    "ἀμνός": "anak domba",
    "ἀμφίβληστρον": "jala",
    "ἀναμάρτητος": "tidak berdosa",
    "ἀναστρέφω": "hidup",
    "ἀνδραποδιστής": "pemburit, laki-laki yang kawin laki-laki",
    "ἀντίλυτρον": "tebusan",
    "ἀντιδικος": "musuh",
    "ἀντιπαρέρχομαι": "melewati dari seberang jalan",
    "ἀνυπόκριτος": "ikhlas, tulus, tidak munafik",
    "ἀνωφελής": "tidak berguna",
    "ἀπαίδευτος": "bodoh, tidak terdidik",
    "ἀπαντάω": "menyongsong, menemui",
    "ἀπατάω": "memperdaya, menipu",
    "ἀπαύγασμα": "cahaya kemuliaan, pancaran",
    "ἀποσυναγωγος": "dikucilkan",
    "ἀπόκριμα": "hukuman",
    "ἀρτέμων": "layar",
    "ἀρχιτρίκλινος": "pemimpin pesta",
    "ἀφεδρών": "jamban, toilet",
    "ἀφθαρτος": "abadi, tidak dapat binasa, tidak fana",
    "ἀφιλάργυρος": "tidak cinta uang",
    "ἀφιλαργυρος": "bukan hamba uang",
    "ἀφρίζω": "berbusa",
    "ἀχρεῖος": "tidak berguna",
    "ἀόρατος": "tidak kelihatan",
    "ἁγιωσύνη": "kekudusan, kesucian",
    "ἁγιότης": "kekudusan, kesucian",
    "ἁγνός": "suci, murni, tidak bersalah",
    "ἁγνῶς": "dengan tulus, dengan murni",
    "ἄγγος": "pasu, tempayan, bejana",
    "ἄγκυρα": "sauh",
    "ἄγριος": "liar",
    "ἄντλημα": "timba",
    "ἄπειμι": "tidak hadir, pergi",
    "ἅγια, ἅγιον": "tempat kudus",
    "Ἀδρίας": "laut Adria",
    "Ἀλεξανδρεύς": "orang Aleksandria",
    "Ἀντιοχεύς": "orang Antiokhia",
    "Ἀραβία": "Arab",
    "Ἀσιανός": "Asia",
    "ἐνδοξάζομαι": "dimuliakan",
    "ἐνδώμησις": "bahan bangunan",
    "ἐξαιρέω": "melepaskan, menyelamatkan",
    "ἐπάγγελμα": "janji",
    "ἐπενδύτης": "pakaian, baju, jubah",
    "ἐσμυρνισμένος": "anggur bercampur mur",
    "ἐφημερία": "rombongan imam yang bertugas",
    "Ἑλληνίς": "Yunani",
    "Ἑλληνιστί": "Bahasa Yunani",
    "ἧλος": "paku",
    "ἰσόψυχος": "sepikir",
    "ἱλαστήριος": "jalan pendamaian",
    "Ἰορδάνης": "Yordan",
    "Ἰσκαριώθ": "Iskariot",
    "Ἱεροσολυμίτης": "dari Yerusalem",
    "ὀνάριον": "keledai muda",
    "ὀφειλή-1": "utang",
    "ὀψάριον": "ikan",
    "ὁλοκαύτωμα": "korban bakaran",
    "ὁρκωμοσία": "sumpah",
    "ὅσιος": "saleh, kudus",
    "ὕσσωπος": "hisop",
    "ῥαββι": "Rabi",
})

HB.update({
    "אֱלֹהִים": "Allah Israel",
    "אֱמֶת": "kebenaran, kesetiaan",
    "אֱמֹרִי": "orang Amori",
    "אֱמוּנָה": "kemantapan, kesetiaan, kepercayaan",
    "אֲגָגִי": "orang Agag",
    "אֲדוֹמִי": "orang Edom",
    "אֲחַזְיָהוּ-1": "Ahazia",
    "אֲמָנָה-1": "sungai Abana",
    "אֲרִי": "singa",
    "אֲרַמִּי": "orang Aram, orang Siria",
    "אֲרָם-1": "Aram, Siria",
    "אֲרוֹן": "tabut (TUHAN), tabut perjanjian",
    "אֲשֵׁרָה-2": "tiang kayu yang berhala",
    "אֵזוֹב": "hisop",
    "אֵילַת": "Elat",
    "אֵלָה-1": "pohon besar, pohon tarbantin",
    "אֵלוֹן-1": "pohon besar, pohon tarbantin",
    "אֵפֹד-4": "efod (berhala)",
    "אֶבֶן הַזֹּחֶלֶת": "Batu Ular, Batu Zohelet",
    "אֶבֶן-2": "batu permata",
    "אֶזְרָחִי": "orang Ezrahi",
    "אֶפְרָתִי-2": "orang Efraim",
    "אֶרֶג": "patok, tarok, perkakas tenun",
    "אֶרֶז": "pohon aras, kayu cemara",
    "אַבִּיר-1": "sapi, lembu atau kuda jantan",
    "אַדִּיר-2": "bangsawan, pemimpin, perwira",
    "אַחְאָב-1": "Ahab",
    "אַיִל-1": "domba jantan",
    "אַיִל-4": "tiang pintu, ambang pintu",
    "אַיָּל": "rusa",
    "אַלְמֻגִּים": "pohon cendana",
    "אַרְבֶּה": "belalang",
    "אַרְגָּמָן": "warna ungu muda",
    "אַרְיֵה-1": "singa",
    "אַרְנוֹן": "sungai Arnon",
    "אָדָם-3": "manusia",
    "אָדוֹן": "tuan, pemilik",
    "אָטָד": "semak duri",
    "אָלָה-1": "kutuk",
    "אָמָה": "budak, pelayan wanita",
    "אָשֵׁרִי": "orang Asyer",
    "אָשָׁם": "korban penebus salah",
    "אָתוֹן": "keledai betina",
    "אֹהֶל מוֹעֵד": "Kemah Pertemuan",
    "אֻרְוָה": "kandang hewan",
    "אוֹב": "ahli nujum",
    "אוֹת-3": "tanda, petunjuk",
    "אוּרִי-2": "Uri",
    "אלה": "kutuk, mengutuk",
    "אמן-1": "benar, setia, teguh",
    "אמן-2": "percaya pada, kepercayaan",
    "ארר": "kutukan",
    "אשׁם": "korban penebus salah, menderita hukuman, menyatakan bersalah",
    "בְּלִיַּעַל": "orang dursila, jahat",
    "בְּרִית": "perjanjian",
    "בְּרָכָה-1": "berkat",
    "בְּרוֹשׁ-1": "pohon cemara, jintan saru",
    "בִּטָחוֹן": "keamanan, tenang",
    "בִּכּוּרִים": "buah pertama, buah bungaran",
    "בֵּית הָאֱלִי": "orang Betel",
    "בֶּטַח-2": "keamanan, tenang",
    "בַּהַט": "pualam, marmar",
    "בַּעֲלָה-1": "nyonya, pemilik",
    "בַּעַל-1": "tuan, pemilik, suami",
    "בַּרְבּוּר": "semacam angsa",
    "בַּרְקָן": "duri",
    "בַּת": "bat (takaran cairan)",
    "בָּקָר": "ternak, lembu, kawanan",
    "בֹּשֶׂם": "pohon balsam, minyak balsam",
    "בּוּץ": "linen halus",
    "בטח": "bersandar pada, mempercayai, memiliki kepercayaan diri",
    "בין": "berakal budi, cerdas, memahami",
    "ברך": "memberkati",
    "גְּבִירָה-1": "nyonya",
    "גְּבִירָה-2": "ratu",
    "גְּבִירָה-3": "ibu ratu",
    "גְּדִי, גְּדִיָּה": "kambing muda",
    "גְּרִזִּים": "gunung Gerizim",
    "גִּבְלִי": "orang Gebal",
    "גֶּפֶן": "pokok anggur",
    "גַּעַשׁ": "gunung Gaas",
    "גַּרְזֶן": "kapak, beliung",
    "גַּת-1": "alat pemeras anggur",
    "גָּדִי-1": "orang Gad",
    "גָּזִית": "batu pahat(an)",
    "גָּמָל": "unta",
    "גֹּדֵר": "tukang batu",
    "גֹּרֶן": "tempat pengirikan",
    "גּוֹי": "bangsa, orang",
    "גּוֹרָל": "undi",
    "דְּבוֹרָה-1": "lebah",
    "דֶּרֶךְ": "jalan (kehidupan, jalan Tuhan)",
    "דַּעַת-1": "pengetahuan",
    "דָּגָן": "biji-bijian, jagung",
    "דָּנִי": "orang Dan",
    "הַלְמוּת": "palu",
    "זְבוּלוֹנִי": "orang Zebulon",
    "זַיִת": "pohon zaitun",
    "זָקֵן": "lebih tua, (jamak) para tua-tua",
    "זנה": "berlaku sebagai pelacur, bersundal",
    "חֲמוֹר-1": "keledai",
    "חֵטְא-1": "dosa",
    "חֵטְא-2": "kesalahan",
    "חֵן-1": "kebaikan, berkenan, kasihan",
    "חֵץ": "panah",
    "חֵרֶם-2": "sesuatu yang dikhususkan untuk Tuhan",
    "חֶרֶב": "pedang, kekerasan, peperangan",
    "חֶרֶב וְקֶשֶׁת": "pedang dan panah/busur, kekuatan militer, prestasi",
    "חַטָּא-2": "menanggung kesalahan",
    "חַיָּה-1": "makhluk hidup, binatang darat, binatang liar",
    "חָכְמָה-1": "keahlian, kemampuan, ketrampilan",
    "חָכְמָה-2": "kebijaksanaan",
    "חָסִיל": "belalang",
    "חָצִיר-1": "rumput",
    "חָרִיט": "pundi, tas",
    "חָרָשׁ": "ahli, tukang",
    "חֹדֶשׁ-1": "pesta bulan baru",
    "חֹק-3": "ketetapan, undang, perintah",
    "חֹר": "pemimpin, pemuka",
    "חֹרֵב": "gunung Horeb",
    "חוֹחַ-1": "semak duri",
    "חוּט-1": "benang",
    "חטא-1": "berbuat dosa",
    "חלה פָּנִים": "memohon dengan sungguh-sungguh bantuan seseorang atau niat baik",
    "חנך": "acara peresmian",
    "חנן-1": "mengaruniakan, bermurah hati, berbelas kasihan",
    "חנן-2": "memohon belas kasihan",
    "חסה-1": "mencari perlindungan",
    "חרם-2": "mengkhususkan, membunuh, memusnahkan",
    "חרשׁ-1": "membajak",
    "טָמֵא": "najis",
    "טֻמְאָה": "kenajisan",
    "טהר": "murni, bersih, tahir",
    "יְבוּסִי": "orang Yebus",
    "יְהוֹשָׁפָט-3": "Yosafat",
    "יְהוּדִי-1": "orang Yehuda, Yahudi",
    "יְמִינִי": "orang Benyamin",
    "יְרֻשָּׁה": "milik",
    "יִזְרְעֵאלִי": "orang Yizreel",
    "יִזְרְעֶאל-2": "Yizreel",
    "יִצְהָר-1": "minyak (zaitun)",
    "יִשְׁרָה": "kejujuran",
    "יִשְׂרָאֵל": "Israel",
    "יֵהוּא-2": "Yehu",
    "יֵרָקוֹן": "jamur, hama, penyakit gandum",
    "יֶקֶב-2": "alat/tempat pemeras anggur",
    "יַבֹּק": "sungai Yabok",
    "יַרְדֵּן": "sungai Yordan",
    "יָרֵא": "keadaan takut, terpesona",
    "יָשָׁר": "lurus, benar, jujur",
    "יָתֵד-1": "patok",
    "יָתֵד-2": "pasak (tenda)",
    "יֹשֶׁר": "kebenaran, kejujuran",
    "ידה-1": "mengakui, memuji, menghormati",
    "יוֹנָה-1": "burung merpati",
    "יצא ובוא": "memimpin",
    "ירשׁ-4": "menguasai, kalahkan, menaklukkan",
    "ירשׁ-5": "mengusir, menghalau",
    "ישׁע": "menolong, menyelamatkan, berikan kemenangan",
    "כְּנַעַן-2": "(tanah) Kanaan",
    "כְּפִיר": "singa muda",
    "כְּרֵתִי-2": "orang Kreti",
    "כְּרוּב-1": "kerub, kerubim (jamak)",
    "כֶּלֶא": "penjara",
    "כֶּלֶב": "anjing",
    "כֶּסֶף": "perak, uang",
    "כֶּרֶם": "kebun anggur",
    "כֶּשֶׁף": "mantera, sihir",
    "כֶּתֶר": "mahkota",
    "כַּר-1": "anak domba, domba jantan dikebiri",
    "כָּבוֹד-1": "kemuliaan, kehadiran Tuhan",
    "כָּבוֹד-2": "kemuliaan, kehormatan, kekayaan",
    "כָּרִי": "orang Kari",
    "כֹּהֵן": "imam",
    "כֹּחַ-2": "kekuatan, hasil tanah, kekayaan",
    "כבד-3": "menghormati, memuliakan, memberi upah",
    "לְבָנוֹן": "gunung Libanon",
    "לֵוִי-2": "orang Lewi",
    "לֶחֶם פָּנִים": "roti sajian, roti kehadiran Tuhan, roti suci",
    "לוּחַ-2": "loh batu, tablet (batu)",
    "מְגֵרָה": "gergaji batu, kikir batu",
    "מְנַשִּׁי": "orang Manasye",
    "מְרִיא": "anak sapi gemuk",
    "מִגְדָּל": "menara",
    "מִקְלַעַת": "ukiran",
    "מִקְנֶה": "hewan peliharaan, ternak",
    "מִרְמָה-1": "penipuan, pengkhianatan",
    "מִשְׁפְּתַיִם": "kandang",
    "מִשְׁפָּחָה": "jenis (hewan)",
    "מַזְכִּיר": "bendahara, perekam, penulis sejarah",
    "מַלְאָךְ-1": "utusan, pesuruh",
    "מַלְאָךְ-2": "malaikat",
    "מַלְכָּה": "ratu",
    "מַלְמַד": "tongkat menggiring",
    "מַעְַלֵה עַקְרַבִּים": "Pendakian/Jalan Akrabim, lereng-lereng di gunung Akrabim",
    "מַצָּה": "roti tidak beragi, roti yang dibuat tanpa ragi",
    "מַקֶּבֶת": "palu",
    "מַשָּׂא-1": "ucapan ilahi, ramalan",
    "מָגֵן-1": "perisai",
    "מָעוֹז": "benteng, tempat berlindung",
    "מָעוֹן-2": "orang Maon",
    "מָשָׁל-1": "pengucapan, amsal, peribahasa",
    "מֹר": "mur, dupa",
    "מוֹאָב": "Moab",
    "מוֹלֶדֶת": "sanak saudara, kaum keluarga",
    "מוֹפֵת-2": "keajaiban, mujizat",
    "מוֹקֵשׁ": "jerat, perangkap",
    "מוֹרֶה-2": "bukit More",
    "מוֹרָה": "pisau cukur",
    "מוֹשִׁיעַ": "pertolongan, keselamatan, penyelamat",
    "מחה-2": "menghancurkan",
    "מרד": "memberontak, melawan",
    "מרה": "memberontak, melawan",
    "משׁח": "mengolesi, meminyaki",
    "נְבָלָה": "tindakan atau kata-kata bodoh",
    "נֵזֶר-2": "mahkota, jamang, hiasan emas",
    "נֶדֶר": "nazar, sumpah, kaul",
    "נֶסֶךְ": "korban curahan, persembahan minuman",
    "נַחֲלָה": "milik, warisan, nasib",
    "נָבִיא": "nabi",
    "נָגִיד": "raja, pemimpin, kepala",
    "נָזִיר": "nazir, mayat, dan memotong rambutnya",
    "נָחָשׁ-1": "ular",
    "נָקִי": "lepas atau bebas dari sumpah, dari kesalahan dan dari hukuman",
    "נָשִׂיא": "raja, tuan, pemuka",
    "נבא": "kepenuhan (roh) seperti nabi, bertindak sebagai seorang nabi",
    "נדר": "bernazar, bersumpah",
    "נקה-1": "lepas atau bebas dari sumpah, dari kesalahan dan dari hukuman",
    "נקה-2": "ucapkan tidak bersalah, untuk melepaskan tanpa hukuman",
    "סִינַי": "gunung Sinai",
    "סֵפֶר": "kitab, daftar, surat",
    "סֶלַע רִמּוֹן": "batu Rimon",
    "סָרִיס": "pengawai, perwira, pejabat istana",
    "סֹפֵר": "panitra negara, penulis, sekretaris",
    "סוּס, סוּסָה": "kuda",
    "סלח": "mengampuni",
    "עֲבוֹדָה": "bekerja, melayani",
    "עֲטָרָה-1": "mahkota, tajuk, karangan bunga",
    "עֲמָלֵק": "Amalek",
    "עֵגֶל-2": "patung anak lembu",
    "עֵדֶר-1": "kumpulan, kawanan",
    "עֵז": "kambing (betina)",
    "עֵץ שֶׁמֶן": "pohon minyak (zaitun)",
    "עֵצָה": "pertimbangan, nasihat, saran",
    "עֶגְלָה-1": "anak sapi betina, sapi muda",
    "עֶצְיוֹן גֶּבֶר": "Ezion-Geber",
    "עַזָּתִי": "orang Gaza",
    "עַיִר": "keledai jantan",
    "עָוֹן": "pelanggaran, dosa, hukuman",
    "עָרֵל-1": "tidak disunat",
    "עֹל": "kuk, penindasan, perbudakan",
    "עבד-1": "ditaklukkan, diperbudak, melayani sebagai hamba",
    "עוֹף": "burung",
    "עוֹרֵב": "burung gagak",
    "פְּרִזִּי": "orang Feris",
    "פִּילֶגֶשׁ": "selir",
    "פִּרְדָּה": "bagal betina",
    "פִּרְעָתוֹנִי": "orang Piraton",
    "פִּתּוּחַ": "ukiran",
    "פֵּשֶׁת-1": "rami, lenan",
    "פֶּחָה-1": "gubernur provinsi",
    "פֶּרֶד": "bagal jantan",
    "פֶּשַׁע": "kesalahan, kejahatan, pelanggaran",
    "פַּקֻּעֹת": "labu liar",
    "פַּרְעֹה": "Firaun",
    "פַּרְפַּר": "sungai Parpar",
    "פָּר": "sapi atau lembu jantan muda",
    "פָּרָשׁ": "kuda (perang)",
    "פָּתִיל-1": "tali, benang",
    "פדה-3": "menebus, membebaskan",
    "פקד-3": "menugaskan, menempatkan, menyerahkan",
    "פשׁע": "memberontak, melanggar, bertengkar",
    "צְדָקָה": "kebenaran, keadilan",
    "צִידֹנִי": "orang Sidon",
    "צִקְלוֹן": "kantong, tas",
    "צֶבַע": "kain dicelup warna",
    "צֶלֶם-2": "(patung) berhala",
    "צֶמֶר": "wol",
    "צַדִּיק": "orang tidak bersalah, orang benar",
    "צַלְמוֹן-1": "gunung Zalmon",
    "צָבָא-2": "makhluk surgawi, tentara Tuhan, Balatentara",
    "צָרַעַת": "penyakit kulit menular",
    "צֹאן": "kawanan",
    "צֹרִי": "orang Tirus",
    "צֹרֵף": "tukang emas",
    "צדק-3": "membenarkan, dinyatakan tidak bersalah",
    "צרע": "menderita penyakit kulit menular dan bahaya",
    "קְלָלָה": "kutukan",
    "קִדְרוֹן": "sungai Kidron",
    "קִנְאָה": "mencurigai, iri hati, cemburu (terhadap isteri)",
    "קֵינִי": "orang Keni",
    "קַו": "garis pengukur",
    "קַיִן-2": "orang Keni",
    "קַרְדֹּם": "kapak",
    "קָדֵשׁ-1": "pelacur kuil laki-laki",
    "קָדוֹשׁ": "khusus, kudus, suci",
    "קָמָה": "gandum yang belum dipanen, berkas gandum yang baru dipotong",
    "קָנֶה-1": "buluh",
    "קדשׁ": "menjadi kudus/khusus, buktikan diri suci, nyatakan suci",
    "קוֹף": "kera",
    "קלע": "mengukir",
    "קנא": "iri hati, cemburu",
    "רְאוּבֵנִי": "orang Ruben",
    "רִמּוֹן-1": "pohon delima",
    "רִקְמָה": "kain bersulam, sulaman",
    "רֶכֶשׁ": "kuda cepat",
    "רֶמֶשׂ": "reptil, binatang melata",
    "רַב־סָרִיס": "kepala petugas di istana",
    "רַב־שָׁקֵה": "kepala penasehat, kepala pengawal raja",
    "רָצוֹן": "berkenan, kepuasan, kesenangan",
    "רָשָׁע": "jahat, murtad",
    "רֹתֶם": "pohon arar atau rindang",
    "רשׁע-2": "menyatakan bersalah",
    "רשׁע-3": "bertindak jahat",
    "שְׁבוּעָה": "sumpah",
    "שְׂעֹרָה": "jelai",
    "שִׁילֹנִי-1": "orang Silo",
    "שִׁקְמָה": "pohon ara",
    "שִׁקּוּץ": "hal yang dibenci, patung berhala",
    "שֵׁבֶט-1": "suku",
    "שֶׁלֶם": "korban perdamaian, korban keselamatan",
    "שֶׂה": "domba",
    "שַׁבָּת": "Sabat, (hari istirahat)",
    "שָׁלוֹם": "damai, tenang, kemakmuran",
    "שֹׁמְרוֹן": "Samaria",
    "שׁוֹר": "sapi, lembu",
    "שׁוּעָל-1": "serigala, anjing hutan, rubah",
    "שׁוּשַׁן-1": "bunga bakung",
    "שׂכל": "memiliki pengertian, menjadi arif, beruntung",
    "תְּאֵנָה": "pohon ara",
    "תְּבוּנָה": "pengertian",
    "תְּחִנָּה-1": "permohonan",
    "תְּרָפִים": "terafim, berhala rumah tangga",
    "תְּשׁוּעָה": "keselamatan",
    "תִּפְסַח-2": "Tifsah",
    "תִּרְצָה-2": "Tirza",
    "תִּשְׁבִּי": "orang Tisbe",
    "תַּרְשִׁישׁ-2": "Tarsis",
    "תַּרְתָּן": "Panglima, Tartan",
    "תָּרְמָה": "penipuan, pengkhianatan",
    "תֹּמֶר": "kurma",
    "תֻּכִּי": "kera, monyet",
    "תּוֹעֵבָה": "kekejian, merasa hina",
    "תּוֹרָה": "hukum, Taurat; pengajaran",
    "תמם": "habis, selesai, lengkap",
})
