# -*- coding: utf-8 -*-
# Tombulu (tom) — nombres propios y compuestos capitalizados.
#
# Generado a partir de los datos de Paratext, no a ojo:
#   · el tipo sale de <Domain> en Terms/Lists/BiblicalTerms.xml
#   · la forma indonesia, de BiblicalTermsId.xml (localización oficial)
#   · TERM_MOVE recoge las formas cuyo lema NO es onomástico para
#     Paratext (Category != PN): son términos traducibles, no nombres.
#
# Las formas que no se pueden sostener con esos datos se han dejado sin
# tocar; siguen apareciendo como nombre propio hasta que el equipo diga
# qué son. Lista al final del fichero.

# (1) Formas capitalizadas que son en realidad TÉRMINOS TRADUCIBLES.
#     Se mueven al diccionario principal con esta glosa indonesia. [B]
TERM_MOVE = {
    "Ama'": "Abba, Bapa",
    "An ikasampetla": "habis, selesai, lengkap",
    "Beruang": "beruang",
    "Empung": "Tuhan",
    "EMPUNG si menou-nou": "Allah semesta alam",
    "Firdaus": "Firdaus",
    "Hesed": "kebaikan, kemurahan, kasih",
    "Hilkia tonaas né witi istana": "kepala penasehat, kepala pengawal raja",
    "Ikuamola": "utusan, pesuruh",
    "Kakolanoan ni Opo Empung": "memberitakan Injil, memberitakan kabar baik",
    "Kakolanoan-Na": "Kerajaan Allah",
    "Kolano Benhadad": "tuan, pemilik",
    "Kuan": "utusan, pesuruh",
    "Lebo Hamat": "gurun, dataran",
    "Legion": "legiun (pasukan Romawi)",
    "Lé'os uman": "damai, tenang, kemakmuran",
    "Mahkamah Agama": "Mahkamah Agama",
    "Mahpiara": "Tuhan",
    "Mahtali-talingala wo mahkiitla wana am péléng an ukum": "memiliki pengertian, menjadi arif, beruntung",
    "Malaékat": "malaikat",
    "Mengalé-ngaléi ni Ko é méhémé genang wia ni aku": "permohonan",
    "Mengalé-ngaléi si Empung, Opo Empung nai é sekezé mahgenang um penginaléién kenu": "memohon belas kasihan",
    "Menunulung": "Penghibur, Penolong, seorang pengantara atau pembela",
    "Milo": "benteng, kubu pertahanan, distrik",
    "Ni Aku é zéi'kan kumana' in tuméiz wo gumenang un tampa itii": "memohon belas kasihan",
    "Ni kai é simingkéla'mola, simala'mola wo nimangunola a léwo'an": "memohon belas kasihan",
    "Ni sia": "raja",
    "Nimeréta": "berbuat dosa",
    "Nuwu": "firman TUHAN",
    "Nuwu'": "firman, ucapan",
    "Nuwu' Lé'os": "memberitakan Injil, memberitakan kabar baik",
    "Nuwu' ni Opo Empung": "memberitakan Injil, memberitakan kabar baik",
    "Oki'    ni Opo Empung": "Anak Allah",
    "Oki' Ni Tou": "Anak Manusia",
    "Oki' ni Tou": "Anak Manusia",
    "Opo Empung": "Allah",
    "Pinantik Lenas": "Kitab Suci, nas",
    "Pondok Daun": "Hari Raya Pondok Daun",
    "Roh Lenas": "Roh Kudus",
    "Roh ni Opo Empung": "Roh Kudus",
    "Roh-Na Lenas": "Roh Kudus",
    "Sabat": "Sabat, (hari istirahat)",
    "Si Pahloozen": "Yang Terpuji (yaitu Allah)",
    "Sungkulenola": "perjumpaan, pertemuan",
    "Sé ringkéng": "burung pipit",
    "Sé tou": "kasihan, mengasihani",
    "Tampa Lenas": "Ruang Mahakudus",
    "Tia'mo maharét": "damai, tenang, kemakmuran",
    "Torat": "hukum, hukum Taurat, kitab Taurat",
    "Totoz  Rumaké-rakék": "Mahatinggi",
    "Totoz wangun": "kebenaran, kesetiaan",
    "Tuang": "tuan, pemilik",
    "Tulungené, é tuangku kolano": "menolong, menyelamatkan, berikan kemenangan",
    "Tutuuzan né sétang": "si pencoba, si penggoda",
    "Ulito": "kebenaran, kesetiaan",
    "Um penginaléiennu én tinalinga-Kumola": "permohonan",
    "Urusenola lé'os": "memperhatikan, memelihara (seseorang, sesuatu)",
    "Walian Wangko'": "imam besar",
    "Walé Ni Opo Empung": "Bait Allah, rumah Allah",
    "Walé ni Opo Empung": "Bait, Bait Allah, Rumah Tuhan",
    "Zéi'kan siapa zozo' in esa si tuama im wia si Baesa si méitula'unama i menou-nou": "sanak, penebus, pembalas",
    "Zéi'kan wangun um pahmualinta": "pelanggaran, dosa, hukuman",
    "Éné": "Amin!",
}

# (2) Nombres propios y su tipo.
PROP = {
    "'Akeldama'": "tempat",
    "Abadon": "lain",
    "Abagta": "orang",
    "Abda": "orang",
    "Abdon": "orang",
    "Abel-Bet-Maakha": "tempat",
    "Abel-Keramim": "tempat",
    "Abel-Mehola": "tempat",
    "Abi": "orang",
    "Abia": "orang",
    "Abiam": "orang",
    "Abida": "orang",
    "Abiezer": "bangsa",
    "abiezer": "orang",
    "abigail": "orang",
    "Abihail": "orang",
    "Abimael": "orang",
    "Abimelekh": "orang",
    "abimelekh": "orang",
    "Abinoam": "orang",
    "Abiram": "orang",
    "Abisag": "orang",
    "abisai": "orang",
    "Abisalom": "orang",
    "Abner": "orang",
    "abner": "orang",
    "Abraham": "orang",
    "abram": "orang",
    "Absalom": "orang",
    "Abyatar": "orang",
    "Adalya": "orang",
    "adam": "orang",
    "Admata": "orang",
    "Adoni-Bezek": "orang",
    "Adonia": "orang",
    "Adoniram": "orang",
    "Adoram": "orang",
    "Adramitium": "orang",
    "adulam": "tempat",
    "Afek": "tempat",
    "agag": "orang",
    "Agripa": "orang",
    "Ahab": "orang",
    "Ahas": "orang",
    "Ahasyweros": "orang",
    "ahasyweros": "orang",
    "Ahazia": "orang",
    "Ahia": "orang",
    "Ahilud": "orang",
    "Ahima'as": "orang",
    "Ahiman": "orang",
    "ahimelekh": "orang",
    "Ahinadab": "orang",
    "ahinoam": "orang",
    "Ahisar": "orang",
    "ahitofel": "orang",
    "Ahlab": "tempat",
    "ai": "tempat",
    "Ainon": "tempat",
    "akhan": "orang",
    "Akhis": "orang",
    "akhis": "orang",
    "Akhsa": "orang",
    "akhsa": "orang",
    "Akhzib": "tempat",
    "Ako": "tempat",
    "Aleksandria": "bangsa",
    "Alot": "tempat",
    "Amalek": "orang",
    "amalek": "orang",
    "Amasa": "orang",
    "amasa": "orang",
    "Amazia": "orang",
    "Amfipolis": "tempat",
    "Amitai": "orang",
    "amnon": "orang",
    "Amon": "orang",
    "Amos": "orang",
    "Ampliatus": "orang",
    "Anat": "orang",
    "Anatot": "tempat",
    "Andronikus": "orang",
    "Antiokhia": "tempat",
    "Antipatris": "tempat",
    "Apeles": "orang",
    "Apolion": "lain",
    "Apolonia": "tempat",
    "Arad": "tempat",
    "Aram": "bangsa",
    "arauna": "orang",
    "Areopagus": "tempat",
    "Aretas": "orang",
    "Argob": "tempat",
    "Aridai": "orang",
    "Aridata": "orang",
    "Arimatea": "tempat",
    "Arisai": "orang",
    "Aristarkus": "orang",
    "Aristobulus": "orang",
    "Arkhipus": "orang",
    "Aroer": "tempat",
    "Aro”er": "tempat",
    "Arpad": "tempat",
    "arpakhsad": "orang",
    "Artemis": "lain",
    "Arubot": "tempat",
    "Aruma": "tempat",
    "Arye": "orang",
    "Arza": "orang",
    "Asa": "orang",
    "asael": "orang",
    "Asaf": "orang",
    "Asdod": "tempat",
    "asdod": "tempat",
    "Asinkritus": "orang",
    "Askelon": "tempat",
    "Asos": "tempat",
    "Aspata": "orang",
    "Astoret": "lain",
    "Asyer": "orang",
    "asyer": "orang",
    "Asyera": "lain",
    "Asytoret": "lain",
    "Asyur": "tempat",
    "Atalia": "tempat",
    "Atalya": "orang",
    "Ayalon": "tempat",
    "ayalon": "tempat",
    "Azarya": "orang",
    "Azarya oki' ni Amazia": "orang",
    "Azuba": "orang",
    "Ba'al": "lain",
    "Ba'al-Salisa": "tempat",
    "Ba'al-Zebub": "lain",
    "Ba'alat": "tempat",
    "Ba'ana": "orang",
    "Baal": "lain",
    "Baal-Berit": "lain",
    "Baal-Hermon": "tempat",
    "Baal-Tamar": "tempat",
    "Baana": "orang",
    "Babel": "tempat",
    "babel": "tempat",
    "Baesa": "orang",
    "Bahurim": "tempat",
    "bahurim": "tempat",
    "Baladan": "orang",
    "Balak": "orang",
    "Barak": "orang",
    "barak": "orang",
    "Barnabas": "orang",
    "Barsabas": "orang",
    "Baryesus": "orang",
    "Barzilai": "orang",
    "barzilai": "orang",
    "Basan": "tempat",
    "Basmat": "orang",
    "basmat": "orang",
    "Batsyeba": "orang",
    "batsyeba": "orang",
    "Beer": "tempat",
    "Belial": "lain",
    "Ben- Hur": "orang",
    "Ben-Abinadab": "orang",
    "Ben-Deker": "orang",
    "Ben-Geber": "orang",
    "Ben-Hesed": "orang",
    "Benaya": "orang",
    "Benhadad": "orang",
    "Benyamin": "orang",
    "Berea": "tempat",
    "Bernike": "orang",
    "Bersyeba": "tempat",
    "Bet-Anat": "tempat",
    "Bet-Bara": "tempat",
    "Bet-Eked": "tempat",
    "Bet-Horon": "tempat",
    "Bet-Rehob": "tempat",
    "Bet-Sean": "tempat",
    "Bet-Semes": "tempat",
    "Bet-Sita": "tempat",
    "Betel": "tempat",
    "Bethesda": "tempat",
    "Betlehem": "tempat",
    "betuel": "orang",
    "Bezek": "tempat",
    "Bidkar": "orang",
    "Bigta": "orang",
    "Bigtan": "orang",
    "bikri": "orang",
    "bilha": "orang",
    "Bizta": "orang",
    "Blastus": "orang",
    "Boas": "tempat",
    "Bokhim": "tempat",
    "Dagon": "lain",
    "dagon": "lain",
    "Dalfon": "orang",
    "Damaris": "orang",
    "Damsyik": "tempat",
    "Dan": "orang",
    "Darda": "orang",
    "Daud": "orang",
    "Debir": "tempat",
    "debir": "tempat",
    "Debora": "orang",
    "debora": "orang",
    "Delila": "orang",
    "Didimus": "orang",
    "dina": "orang",
    "Dodo": "orang",
    "Dor": "tempat",
    "dor": "tempat",
    "Dotan": "tempat",
    "Ebed": "orang",
    "eber": "orang",
    "Ebzan": "orang",
    "eden": "tempat",
    "Edom": "bangsa",
    "Efraim": "orang",
    "efron": "orang",
    "Eglon": "orang",
    "eglon": "orang",
    "Ehud": "orang",
    "ehud": "orang",
    "Ekron": "tempat",
    "Ela": "orang",
    "Eleazar": "orang",
    "eleazar": "orang",
    "Eli": "orang",
    "eli": "orang",
    "Elia": "orang",
    "elifas": "orang",
    "Elihoref": "orang",
    "Elisa": "orang",
    "elkana": "orang",
    "Elon": "orang",
    "elon": "orang",
    "Elon-Bet-Hanan": "tempat",
    "Elot": "tempat",
    "Elyada": "orang",
    "Elyakim": "orang",
    "Emaus": "tempat",
    "EMPUNG": "lain",
    "En-Rogel": "tempat",
    "Enak": "orang",
    "Eneas": "orang",
    "enos": "orang",
    "Epafras": "orang",
    "Epafroditus": "orang",
    "Epenetus": "orang",
    "Esau": "orang",
    "esau": "orang",
    "Ester": "orang",
    "ester": "orang",
    "Esytaol": "tempat",
    "esytaol": "tempat",
    "Etam": "tempat",
    "Etan": "orang",
    "Etbaal": "orang",
    "Etiopia": "tempat",
    "Euodia": "orang",
    "Ezion-Geber": "tempat",
    "Filistin": "bangsa",
    "Filologus": "orang",
    "Firaon": "lain",
    "Firaun": "orang",
    "Flegon": "orang",
    "Forum Apius": "tempat",
    "Fébe": "orang",
    "Gaal": "orang",
    "gaal": "orang",
    "Gabata": "tempat",
    "Gadi": "orang",
    "Galilea": "tempat",
    "Galio": "orang",
    "Gat": "tempat",
    "Gat-Hefer": "tempat",
    "Gaza": "tempat",
    "Geba": "tempat",
    "geba": "tempat",
    "Gebah": "tempat",
    "Geber": "orang",
    "Gehazi": "orang",
    "Genesaret": "tempat",
    "Genubat": "orang",
    "Gera": "orang",
    "gera": "orang",
    "gerar": "tempat",
    "Gersom": "orang",
    "gesur": "tempat",
    "Gezer": "tempat",
    "Gibea": "tempat",
    "gibea": "tempat",
    "Gibeon": "tempat",
    "Gibeton": "tempat",
    "Gideom": "tempat",
    "Gideon": "orang",
    "gideon": "orang",
    "Gihon": "tempat",
    "Gilead": "tempat",
    "Gilgal": "tempat",
    "Ginat": "orang",
    "goliat": "orang",
    "gomora": "tempat",
    "gosyen": "tempat",
    "Gozan": "tempat",
    "Gur": "tempat",
    "Hadad": "orang",
    "Hadadezer": "orang",
    "Hadasa": "orang",
    "Hagar": "orang",
    "hagar": "orang",
    "Hagit": "orang",
    "Halah": "tempat",
    "ham": "orang",
    "Haman": "orang",
    "haman": "orang",
    "Hamat": "tempat",
    "Hamat-Yehuda": "tempat",
    "Hamedata": "orang",
    "hana": "orang",
    "Hanani": "orang",
    "Har-Heres": "tempat",
    "Harbona": "orang",
    "Harod": "tempat",
    "Haroset-Hagoyim": "tempat",
    "Harun": "orang",
    "harun": "orang",
    "Hatah": "orang",
    "hatah": "orang",
    "Hazael": "orang",
    "Hazor": "tempat",
    "Heber": "orang",
    "Hebron": "tempat",
    "hebron": "tempat",
    "Hefer": "tempat",
    "Hegai": "orang",
    "Helba": "tempat",
    "Heman": "orang",
    "Hemor": "orang",
    "hemor": "orang",
    "Hena": "tempat",
    "henokh": "orang",
    "Heres": "tempat",
    "Hermas": "orang",
    "Hermes": "orang",
    "hermon": "tempat",
    "Herodion": "orang",
    "Hesybon": "tempat",
    "Het": "bangsa",
    "Hewi": "bangsa",
    "Hezion": "orang",
    "hezron": "orang",
    "Hiel": "orang",
    "Hierapolis": "tempat",
    "Hilel": "orang",
    "Hilkia": "orang",
    "Hiram": "orang",
    "Hizkia": "orang",
    "Hobab": "orang",
    "Horeb": "tempat",
    "hori": "orang",
    "Horma": "tempat",
    "Hosea": "orang",
    "Hosea oki' ni Ela": "orang",
    "Husai": "orang",
    "husai": "orang",
    "Ibrani": "bangsa",
    "Ido": "orang",
    "Ilirikum": "tempat",
    "India": "tempat",
    "Isai": "orang",
    "Isakhar": "orang",
    "Ishak": "orang",
    "Iskariot": "orang",
    "Ismael": "bangsa",
    "ismael": "orang",
    "Israel": "orang",
    "Israél": "orang",
    "itai": "orang",
    "Italia": "tempat",
    "Iwa": "tempat",
    "Iyon": "tempat",
    "Izebel": "orang",
    "Kabul": "tempat",
    "Kadesh": "tempat",
    "kadesh": "tempat",
    "Kaisar": "lain",
    "Kaisarea": "tempat",
    "Kaleb": "orang",
    "kaleb": "orang",
    "Kalkol": "orang",
    "Kamon": "tempat",
    "Kamos": "lain",
    "Kana": "tempat",
    "Kanaan": "bangsa",
    "Kandake": "lain",
    "Karkas": "orang",
    "Karkor": "tempat",
    "Karsena": "orang",
    "Kauda": "tempat",
    "Kedes": "tempat",
    "Kedesh": "tempat",
    "kedesh": "tempat",
    "Kefas": "orang",
    "kehila": "tempat",
    "Kembu'an Hakor": "tempat",
    "Kena'ana": "orang",
    "Kenas": "orang",
    "kenas": "orang",
    "Kentur Karmel": "tempat",
    "Kerit": "tempat",
    "Kidron": "tempat",
    "Kilikia": "tempat",
    "Kinerot": "tempat",
    "Kir": "tempat",
    "Kir-Hareset": "tempat",
    "Kirene": "tempat",
    "Kiryat-Arba": "tempat",
    "Kiryat-Sefer": "tempat",
    "Kiryat-Yearim": "tempat",
    "Kish": "orang",
    "Kitron": "tempat",
    "Klaudius": "orang",
    "Klemens": "orang",
    "Kleopas": "orang",
    "Klopas": "orang",
    "Knidus": "tempat",
    "Kolose": "tempat",
    "Kornelius": "orang",
    "Kos": "tempat",
    "Kusyan-Risyataim": "orang",
    "Kwartus": "orang",
    "Kéngkréa": "tempat",
    "laban": "orang",
    "Lais": "tempat",
    "Lakhis": "tempat",
    "lamekh": "orang",
    "Lapidot": "orang",
    "Lazarus": "orang",
    "lea": "orang",
    "Lebona": "tempat",
    "Lehi": "tempat",
    "Lewi": "orang",
    "Libia": "tempat",
    "Libna": "tempat",
    "Lidia": "orang",
    "Likaonia": "tempat",
    "Likia": "tempat",
    "Lukius": "orang",
    "Lus": "tempat",
    "lus": "tempat",
    "Maakha": "orang",
    "Madai": "orang",
    "Mahanaim": "tempat",
    "mahanaim": "tempat",
    "Mahol": "orang",
    "Makas": "tempat",
    "makeda": "tempat",
    "Makhir": "orang",
    "makhir": "orang",
    "Malkhus": "orang",
    "mamre": "tempat",
    "Manasye": "orang",
    "Manoah": "orang",
    "manoah": "orang",
    "Maria tou Magdala": "orang",
    "Marsena": "orang",
    "Matan": "orang",
    "Media": "orang",
    "mefiboset": "orang",
    "Megido": "tempat",
    "Mehuman": "orang",
    "Memukan": "orang",
    "Menahem": "orang",
    "Menara-Sikhem": "tempat",
    "Meres": "orang",
    "Merodakh": "orang",
    "Meros": "tempat",
    "Mesa": "orang",
    "Mesias": "lain",
    "Mesir": "orang",
    "Mesopotamia": "tempat",
    "Midian": "orang",
    "Mikha": "orang",
    "mikhal": "orang",
    "mikhmas": "tempat",
    "milka": "orang",
    "Milkom": "lain",
    "Minit": "tempat",
    "Misraim": "orang",
    "Mizpa": "tempat",
    "Moab": "orang",
    "Molokh": "lain",
    "Mordekhai": "orang",
    "mordekhai": "orang",
    "Musa": "orang",
    "Na'aman": "orang",
    "Naama": "orang",
    "nabal": "orang",
    "Nabi Natan": "orang",
    "Nabot": "orang",
    "Nadab": "orang",
    "Naftali": "orang",
    "Nahalol": "tempat",
    "nahor": "orang",
    "Narkisus": "orang",
    "Natan": "orang",
    "Natanael": "orang",
    "Nebat": "orang",
    "Nebukadnezar": "orang",
    "Negeb": "tempat",
    "negeb": "tempat",
    "Nehustan": "tempat",
    "Ner": "orang",
    "ner": "orang",
    "Nereus": "orang",
    "Nikodemus": "orang",
    "Nimfa": "orang",
    "Nimsi": "orang",
    "Nobah": "tempat",
    "nuh": "orang",
    "Numuwu": "lain",
    "Nun": "orang",
    "Obaja": "orang",
    "obed": "orang",
    "Ofir": "orang",
    "Ofra": "tempat",
    "ofra": "tempat",
    "Og": "orang",
    "og": "orang",
    "oholibama": "orang",
    "Olimpas": "orang",
    "Omri": "orang",
    "Onesimus": "orang",
    "Oreb": "orang",
    "Otniel": "orang",
    "padan": "tempat",
    "Paran": "tempat",
    "Parmasta": "orang",
    "Parsandata": "orang",
    "Paruah": "orang",
    "Pasong Asin": "tempat",
    "Patrobas": "orang",
    "Pekah": "orang",
    "Pekah oki' ni Remalya": "orang",
    "Pekahya": "orang",
    "Pekahya oki' ni Menahem": "orang",
    "Pentakosta": "lain",
    "Persia": "bangsa",
    "Persis": "orang",
    "Pinehas": "orang",
    "pinehas": "orang",
    "Piraton": "tempat",
    "Pleti": "bangsa",
    "pleti": "bangsa",
    "Pnuel": "tempat",
    "Porata": "orang",
    "potifar": "orang",
    "Pua": "orang",
    "Pul": "orang",
    "Pura": "orang",
    "raba": "tempat",
    "rahab": "orang",
    "rahel": "orang",
    "Rama": "tempat",
    "Ramat Lehi": "tempat",
    "Ramot": "tempat",
    "Ramot-Gilead": "tempat",
    "refaim": "bangsa",
    "Rehabeam": "orang",
    "Rehob": "tempat",
    "rehob": "tempat",
    "Rei": "orang",
    "Rekhab": "orang",
    "Remalya": "orang",
    "Rezin": "orang",
    "Rezon": "orang",
    "Ribka": "orang",
    "ribka": "orang",
    "Rimon": "lain",
    "Roma": "tempat",
    "Ruben": "orang",
    "Sa'albim": "tempat",
    "Saasgas": "orang",
    "safan": "orang",
    "Safat": "orang",
    "Salim": "tempat",
    "Salmaneser": "orang",
    "Salmuna": "orang",
    "salmuna": "orang",
    "Salomo": "orang",
    "Salum": "orang",
    "Salum oki' ni Yabesh": "orang",
    "Samaria": "tempat",
    "Samgar": "orang",
    "Samir": "tempat",
    "samuel": "orang",
    "Sanherib": "orang",
    "sara": "orang",
    "sarai": "orang",
    "Sarfat": "tempat",
    "Sartan": "tempat",
    "saul": "orang",
    "seba": "orang",
    "Sebna": "orang",
    "Sefarwaim": "tempat",
    "Seir": "orang",
    "seir": "orang",
    "Seira": "tempat",
    "Sela": "tempat",
    "sem": "orang",
    "Semaya": "orang",
    "Semer": "orang",
    "Sesai": "orang",
    "set": "orang",
    "Setar": "orang",
    "Sidon": "orang",
    "Sihon": "orang",
    "sihon": "orang",
    "Sikhar": "tempat",
    "Sikhem": "tempat",
    "Sila": "tempat",
    "Silhi": "orang",
    "Silo": "tempat",
    "Simeat": "orang",
    "Simei": "orang",
    "Simeon": "orang",
    "simeon": "orang",
    "Simson": "orang",
    "Sintikhe": "orang",
    "Sion": "tempat",
    "Siprus": "tempat",
    "Sirtis": "tempat",
    "Sisak": "orang",
    "Sisera": "orang",
    "sisera": "orang",
    "So'so'an Habor": "tempat",
    "So'so'an Yordan": "tempat",
    "sodom": "tempat",
    "Sokho": "tempat",
    "Somer": "orang",
    "Sorek": "tempat",
    "Sosipater": "orang",
    "So’so’an Kison": "tempat",
    "Spanyol": "tempat",
    "Stakhis": "orang",
    "Stefanus": "orang",
    "Sukot": "tempat",
    "Sunem": "tempat",
    "Sur": "tempat",
    "Susan": "tempat",
    "Syeba": "orang",
    "Syisya": "orang",
    "Ta'anakh": "tempat",
    "Tabat": "tempat",
    "Tabor": "tempat",
    "tabor": "tempat",
    "Tabrimon": "orang",
    "Tafat": "orang",
    "Tahpenes": "orang",
    "Talmai": "orang",
    "Talun Libanon": "tempat",
    "Tamar": "tempat",
    "tapuah": "tempat",
    "Tarsis": "orang",
    "Tasik Teberau": "tempat",
    "Tebes": "tempat",
    "Teofilus": "orang",
    "terah": "orang",
    "Teresh": "orang",
    "Tertius": "orang",
    "Tiberias": "tempat",
    "Tibni": "orang",
    "Tifsah": "tempat",
    "Tiglat-Pileser": "orang",
    "Timna": "bangsa",
    "Timnat-Heres": "tempat",
    "Tirus": "tempat",
    "Tirza": "tempat",
    "Tob": "tempat",
    "Tola": "orang",
    "Tou Berea": "bangsa",
    "Tou Efraim": "bangsa",
    "Trifena": "orang",
    "Trifosa": "orang",
    "Urbanus": "orang",
    "Uri": "orang",
    "Uria": "orang",
    "uza": "orang",
    "Uzia": "orang",
    "Waizata": "orang",
    "Walian Uria": "orang",
    "Wasti": "orang",
    "wasti": "orang",
    "Yabesh": "tempat",
    "Yabin": "orang",
    "Yael": "orang",
    "yael": "orang",
    "yafet": "orang",
    "Yahas": "tempat",
    "Yahudi": "bangsa",
    "Yair": "orang",
    "yair": "orang",
    "Yakhin": "tempat",
    "Yakub": "orang",
    "Yanoah": "tempat",
    "Yason": "orang",
    "Yebus": "tempat",
    "Yefta": "orang",
    "yefta": "orang",
    "Yehu": "orang",
    "Yehuda": "bangsa",
    "Yekholya": "orang",
    "Yekhonya": "orang",
    "Yerikho": "tempat",
    "Yerobeam": "orang",
    "Yerobeam oki' ni Nebat": "orang",
    "Yerobeam oki' ni Yoas": "orang",
    "Yerubaal": "orang",
    "yerubaal": "orang",
    "Yerusa": "orang",
    "Yerusalem": "tempat",
    "Yesaya": "orang",
    "Yeter": "orang",
    "Yibleam": "tempat",
    "Yimla": "orang",
    "Yizre'el": "tempat",
    "Yoab": "orang",
    "Yoadan": "orang",
    "Yoah": "orang",
    "Yoahas": "orang",
    "Yoas": "orang",
    "Yoas oki' ni Yoahas": "orang",
    "Yoel": "orang",
    "Yogbeha": "tempat",
    "Yokmeam": "tempat",
    "Yokte'el": "tempat",
    "Yonadab": "orang",
    "Yonatan": "orang",
    "yonatan": "orang",
    "Yope": "tempat",
    "Yoram": "orang",
    "Yoram oki' ni Ahab": "orang",
    "Yosafat": "bangsa",
    "Yoseba": "orang",
    "Yosia": "orang",
    "Yosua": "orang",
    "Yotam": "orang",
    "Yoyada": "orang",
    "yoyakhin": "orang",
    "yoyakim": "orang",
    "Yozabad": "orang",
    "Yulia": "orang",
    "Yulius": "orang",
    "Yunani": "bangsa",
    "Yunias": "orang",
    "Yunus": "orang",
    "Yustus": "orang",
    "Yusuf": "orang",
    "Zaanaim": "tempat",
    "Zabut": "orang",
    "Zadok": "orang",
    "Zair": "tempat",
    "Zakharia": "orang",
    "Zakharia oki' ni Yerobeam": "orang",
    "Zakheus": "orang",
    "Zebah": "orang",
    "zebah": "orang",
    "Zebul": "orang",
    "Zebulon": "orang",
    "zebulon": "orang",
    "Zedekia": "orang",
    "Zeeb": "orang",
    "Zefat": "tempat",
    "zerah": "orang",
    "Zereda": "tempat",
    "Zerera": "tempat",
    "Zeresh": "orang",
    "Zerua": "orang",
    "Zeruya": "orang",
    "Zetar": "orang",
    "ziba": "orang",
    "zif": "tempat",
    "ziklag": "tempat",
    "zilpa": "orang",
    "Zimri": "orang",
    "Zipor": "orang",
    "zoar": "tempat",
    "Zoba": "tempat",
    "Zora": "tempat",
    "zora": "tempat",
}

# (3) Forma estándar en indonesio, cuando difiere de la tombulu.
PROP_ID = {
    "'Akeldama'": "Hakal-Dama (berarti Tanah Darah)",
    "Abadon": "Abadon (berarti Perusak)",
    "abiezer": "Abiezer",
    "abigail": "Abigail",
    "abimelekh": "Abimelekh",
    "abisai": "Abisai",
    "abner": "Abner",
    "abram": "Abram",
    "adam": "Adam",
    "Adramitium": "dari Adramitium",
    "adulam": "Adulam",
    "agag": "Agag",
    "ahasyweros": "Ahasyweros",
    "Ahima'as": "Ahimaas",
    "ahimelekh": "Ahimelekh",
    "ahinoam": "Ahinoam",
    "ahitofel": "Ahitofel",
    "ai": "Ai",
    "akhan": "Akhan",
    "akhis": "Akhis",
    "akhsa": "Akhsa",
    "Aleksandria": "dari Aleksandria",
    "Alot": "Bealot",
    "amalek": "Amalek",
    "amasa": "Amasa",
    "amnon": "Amnon",
    "Apolion": "Abadon (berarti Perusak)",
    "arauna": "Arauna",
    "Aristarkus": "Aristarkhus",
    "Aro”er": "Aroer",
    "arpakhsad": "Arpakhsad",
    "asael": "Asael",
    "asdod": "Asdod",
    "Astoret": "Asytoret",
    "asyer": "Asyer",
    "ayalon": "Ayalon",
    "Azarya oki' ni Amazia": "Azarya",
    "Ba'al": "Baal",
    "Ba'al-Salisa": "Baal-Salisa",
    "Ba'al-Zebub": "Baal-Zebub",
    "Ba'alat": "Baalat",
    "Ba'ana": "Baana",
    "babel": "Babel",
    "Baesa": "Baasa",
    "bahurim": "Bahurim",
    "barak": "Barak",
    "Barnabas": "Barsabas",
    "barzilai": "Barzilai",
    "basmat": "Basmat",
    "batsyeba": "Batsyeba",
    "Ben- Hur": "Ben-Hur",
    "Bethesda": "Betesda",
    "betuel": "Betuel",
    "bikri": "Bikri",
    "bilha": "Bilha",
    "dagon": "Dagon",
    "debir": "Debir",
    "debora": "Debora",
    "dina": "Dina",
    "dor": "Dor",
    "eber": "Eber",
    "Ebzan": "Ibzan",
    "eden": "Eden",
    "efron": "Efron",
    "eglon": "Eglon",
    "ehud": "Ehud",
    "eleazar": "Eleazar",
    "eli": "Eli",
    "elifas": "Elifas",
    "elkana": "Elkana",
    "elon": "Elon",
    "EMPUNG": "YHWH / Yahweh / TUHAN",
    "enos": "Enos",
    "esau": "Esau",
    "ester": "Ester",
    "esytaol": "Esytaol",
    "Firaon": "Firaun",
    "Fébe": "Febe",
    "gaal": "Gaal",
    "geba": "Geba",
    "Gebah": "Geba",
    "gera": "Gera",
    "gerar": "Gerar",
    "gesur": "Gesur",
    "gibea": "Gibea",
    "gideon": "Gideon",
    "goliat": "Goliat",
    "gomora": "Gomora",
    "gosyen": "Gosyen",
    "hagar": "Hagar",
    "ham": "Ham",
    "haman": "Haman",
    "Hamat-Yehuda": "Hamat",
    "hana": "Hana",
    "harun": "Harun",
    "hatah": "Hatah",
    "hebron": "Hebron",
    "hemor": "Hemor",
    "henokh": "Henokh",
    "hermon": "Hermon",
    "Hesybon": "Hesbon",
    "hezron": "Hezron",
    "Horeb": "gunung Horeb",
    "hori": "Hori",
    "Hosea oki' ni Ela": "Hosea",
    "husai": "Husai",
    "ismael": "Ismael",
    "Israél": "Israel",
    "itai": "Itai",
    "kadesh": "Kadesh",
    "kaleb": "Kaleb",
    "Kedes": "Kedesh",
    "kedesh": "Kedesh",
    "kehila": "Kehila",
    "Kena'ana": "Kenaana",
    "kenas": "Kenas",
    "Kentur Karmel": "gunung Karmel",
    "Kir-Hareset": "Kir-Heres",
    "Kéngkréa": "Kengkrea",
    "laban": "Laban",
    "lamekh": "Lamekh",
    "lea": "Lea",
    "lus": "Lus",
    "mahanaim": "Mahanaim",
    "makeda": "Makeda",
    "makhir": "Makhir",
    "mamre": "Mamre",
    "manoah": "Manoah",
    "mefiboset": "Mefiboset",
    "Menara-Sikhem": "Menara Sikhem",
    "Merodakh": "Merodakh-Baladan",
    "mikhal": "Mikhal",
    "mikhmas": "Mikhmas",
    "milka": "Milka",
    "mordekhai": "Mordekhai",
    "Na'aman": "Naaman",
    "nabal": "Nabal",
    "Nabi Natan": "Natan",
    "nahor": "Nahor",
    "negeb": "Negeb",
    "ner": "Ner",
    "nuh": "Nuh",
    "Numuwu": "(Bahasa) Aram",
    "obed": "Obed",
    "ofra": "Ofra",
    "og": "Og",
    "oholibama": "Oholibama",
    "padan": "Padan",
    "Pasong Asin": "Lembah Asin",
    "Pekah oki' ni Remalya": "Pekah",
    "Pekahya oki' ni Menahem": "Pekahya",
    "pinehas": "Pinehas",
    "pleti": "Pleti",
    "potifar": "Potifar",
    "raba": "Raba",
    "rahab": "Rahab",
    "rahel": "Rahel",
    "Ramat Lehi": "Ramat-Lehi",
    "refaim": "Refaim",
    "rehob": "Rehob",
    "ribka": "Ribka",
    "Sa'albim": "Saalbim",
    "safan": "Safan",
    "salmuna": "Salmuna",
    "Salum oki' ni Yabesh": "Salum",
    "samuel": "Samuel",
    "sara": "Sara",
    "sarai": "Sarai",
    "saul": "Saul",
    "seba": "Seba",
    "seir": "Seir",
    "sem": "Sem",
    "set": "Set",
    "sihon": "Sihon",
    "simeon": "Simeon",
    "sisera": "Sisera",
    "So'so'an Habor": "sungai Habor",
    "So'so'an Yordan": "sungai Arnon",
    "sodom": "Sodom",
    "Sokho": "Sohko",
    "So’so’an Kison": "sungai Kison",
    "Susan": "Susa",
    "Syisya": "Sisa",
    "Ta'anakh": "Taanakh",
    "tabor": "Tabor",
    "Tahpenes": "Firaun",
    "Talun Libanon": "gunung Libanon",
    "Tamar": "Tadmor",
    "tapuah": "Tapuah",
    "terah": "Terah",
    "Tirus": "Tirus (harfiah: Zur)",
    "Tou Berea": "orang Berea",
    "Tou Efraim": "orang Efraim",
    "uza": "Uza",
    "Walian Uria": "Uria",
    "wasti": "Wasti",
    "yael": "Yael",
    "yafet": "Yafet",
    "yair": "Yair",
    "yefta": "Yefta",
    "Yerobeam": "Yeroboam",
    "Yerobeam oki' ni Nebat": "Yeroboam",
    "Yerobeam oki' ni Yoas": "Yeroboam",
    "yerubaal": "Yerubaal",
    "Yizre'el": "Yizreel",
    "Yoas oki' ni Yoahas": "Yoas",
    "Yokte'el": "Yokteel",
    "yonatan": "Yonatan",
    "Yoram oki' ni Ahab": "Yoram",
    "Yosafat": "Edom",
    "yoyakhin": "Yoyakhin",
    "yoyakim": "Yoyakim",
    "Zaanaim": "Zaananim",
    "Zakharia oki' ni Yerobeam": "Zakharia",
    "zebah": "Zebah",
    "zebulon": "Zebulon",
    "zerah": "Zerah",
    "ziba": "Ziba",
    "zif": "Zif",
    "ziklag": "Ziklag",
    "zilpa": "Zilpa",
    "zoar": "Zoar",
    "zora": "Zora",
}

# --- PENDIENTE PARA EL EQUIPO ---------------------------------------------
# Formas capitalizadas que Paratext no identifica y cuyo significado no se
# puede sostener con [A] ni [B]. No se han tocado a propósito.
#
#   adar · ahima'as · arba · arki · ba'ana · ben · el · etiopia · gilboa
#   haran · hesybon · isboset · kasdim · kehat · keni · kiryat · kreti
#   ma'akha · makhpela · nebukadnezar · purim · sean · susan · timna
#   yearim
